[msg TUTORIAL_MSG01 [Salvar]]
[s]Pode salvar o jogo pressionando[clr 2][f 1 10 62][clr 27].[n]Quando visualizar o [clr 2] [clr 27]lugar relativo,[n][clr 2]salve a qualquer momento[clr 27].[n][w][e]

[msg TUTORIAL_MSG01_Fiber_NX [Salvar]]
[s]Pode salvar o jogo pressionando[clr 2][f 1 10 62][clr 27].[n]Quando visualizar o [clr 2] [clr 27]lugar relativo,[n][clr 2]salve a qualquer momento[clr 27].[n][w][e]

[msg TUTORIAL_MSG01_Fiber_PS5 [Salvar]]
[s]Pode salvar o jogo pressionando[clr 2][f 1 10 62][clr 27].[n]Quando visualizar o [clr 2] [clr 27]lugar relativo,[n][clr 2]salve a qualquer momento[clr 27].[n][w][e]

[msg TUTORIAL_MSG01_Fiber_Xbo [Salvar]]
[s]Pode salvar o jogo pressionando[clr 2][f 1 10 62][clr 27].[n]Quando visualizar o [clr 2] [clr 27]lugar relativo,[n][clr 2]salve a qualquer momento[clr 27].[n][w][e]

[msg TUTORIAL_MSG01_Fiber_Ste [Salvar]]
[s]Pode salvar o jogo pressionando[clr 2][f 1 10 62][clr 27].[n]Quando visualizar o [clr 2] [clr 27]lugar relativo,[n][clr 2]salve a qualquer momento[clr 27].[n][w][e]

