[msg D_TUTORIAL_24_mes01 [Salas de espera]]
[s]Ocasionalmente, você encontrará [clr 2]Salas[clr 27] em Mementos.[n]Assim como nas Salas Seguras, aqui[n]você pode fazer uma [clr 2]Viagem rápida[clr 27] e [clr 2]salvar o seu jogo[clr 27].[n][w][e]

[msg D_TUTORIAL_24_mes01_NX [Salas de espera]]
[s]Ocasionalmente, você encontrará [clr 2]Salas[clr 27] em Mementos.[n]Assim como nas Salas Seguras, aqui[n]você pode fazer uma [clr 2]Viagem rápida[clr 27] e [clr 2]salvar o seu jogo[clr 27].[n][w][e]

[msg D_TUTORIAL_24_mes01_PS5 [Salas de espera]]
[s]Ocasionalmente, você encontrará [clr 2]Salas[clr 27] em Mementos.[n]Assim como nas Salas Seguras, aqui[n]você pode fazer uma [clr 2]Viagem rápida[clr 27] e [clr 2]salvar o seu jogo[clr 27].[n][w][e]

[msg D_TUTORIAL_24_mes01_Xbox [Salas de espera]]
[s]Ocasionalmente, você encontrará [clr 2]Salas[clr 27] em Mementos.[n]Assim como nas Salas Seguras, aqui[n]você pode fazer uma [clr 2]Viagem rápida[clr 27] e [clr 2]salvar o seu jogo[clr 27].[n][w][e]

[msg D_TUTORIAL_24_mes01_Stea [Salas de espera]]
[s]Ocasionalmente, você encontrará [clr 2]Salas[clr 27] em Mementos.[n]Assim como nas Salas Seguras, aqui[n]você pode fazer uma [clr 2]Viagem rápida[clr 27] e [clr 2]salvar o seu jogo[clr 27].[n][w][e]

