[msg D_TUTORIAL_07_mes01 [As salas seguras]]
[s]Na Sala Segura, você pode [clr 2]consultar seus [n]colegas[clr 27] e [clr 2]salve seu jogo[clr 27] pressionando [clr 2][f 1 10 62][clr 27]. [n]Você também pode [clr 2]salvar [clr 27]na entrada do Palácio.[n][w][e]

[msg D_TUTORIAL_07_mes01_Fibe [Salas seguras]]
[s]Na Sala Segura, você pode [clr 2]consultar seus [n]colegas[clr 27] e [clr 2]salve seu jogo[clr 27] pressionando [clr 2][f 1 10 62][clr 27]. [n]Você também pode [clr 2]salvar [clr 27]na entrada do Palácio.[n][w][e]

[msg D_TUTORIAL_07_mes01_Fibe_2 [Salas seguras]]
[s]Na Sala Segura, você pode [clr 2]consultar seus [n]colegas[clr 27] e [clr 2]salve seu jogo[clr 27] pressionando [clr 2][f 1 10 62][clr 27]. [n]Você também pode [clr 2]salvar [clr 27]na entrada do Palácio.[n][w][e]

[msg D_TUTORIAL_07_mes01_Fibe_3 [Salas seguras]]
[s]Na Sala Segura, você pode [clr 2]consultar seus [n]colegas[clr 27] e [clr 2]salve seu jogo[clr 27] pressionando [clr 2][f 1 10 62][clr 27]. [n]Você também pode [clr 2]salvar [clr 27]na entrada do Palácio.[n][w][e]

[msg D_TUTORIAL_07_mes01_Fibe_4 [Salas seguras]]
[s]Na Sala Segura, você pode [clr 2]consultar seus [n]colegas[clr 27] e [clr 2]salve seu jogo[clr 27] pressionando [clr 2][f 1 10 62][clr 27]. [n]Você também pode [clr 2]salvar [clr 27]na entrada do Palácio.[n][w][e]

