[msg TUTORIAL_MSG01 [Leitura de títulos especiais]]
[s]Escolher "Leitura especial de títulos" ao passar um tempo com[n] os Confidants pode alterar a cor de algumas[n]opções de diálogo.[n][w][e]

[msg TUTORIAL_MSG02 [Leitura de títulos especiais]]
[s]A opção destacada aumentará seu vínculo com[n]aquele Confidente. No entanto, tenha em mente que [clr 2]algumas[n]respostas podem mudar a natureza de[n]seu relacionamento[clr 27], então escolha com cuidado.[n][w][e]

