[msg TUTORIAL_MSG01 [Covil dos Ladrões]]
[s]O [clr 2]Covil dos Ladrões[clr 27] foi desbloqueado. Você pode acessar[n]o Covil dos Ladrões no [f 1 10 25] [clr 2]menu[clr 27] ou[n]na [clr 2]Tela de título[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Covil dos Ladrões]]
[s]No Covil dos Ladrões você pode realizar várias atividades,[n]como ver fotos, ouvir música ou jogar cartas.[n]Você pode desbloquear mais coias a medida que[n]avança na história, então apareça de vez em quando.[n][w][e]

