[msg TUTORIAL_MSG01 [Desafio de batalha]]
[s]Você pode acessar o Desafio de batalha conversando[n]com as Guardiões na Sala de Veludo.[n][w][e]

[msg TUTORIAL_MSG02 [Desafio de batalha]]
[s]Nos desafio de batalha, você enfrenta inimigos com[n]seu grupo, para estabelecer um recorde ao causar[n]o máximo de dano possível.[n][w][e]

[msg TUTORIAL_MSG03 [Desafio de batalha]]
[s]Com base na sua pontuação, você receberá uma[n]recompensa das guardiões.[n][w][e]

[msg TUTORIAL_MSG04 [Desafio de batalha]]
[s]Após a batalha, o HP e SP são restaurados.[n]Os itens consumidos não são devolvidos.[n]Se você perder, o jogo não termina.[n][w][e]

[msg TUTORIAL_MSG05 [Desafio de batalha]]
[s]Fictício[n][w][e]

