[msg TUTORIAL_MSG01 [Alarme de Fusão]]
[s][clr 2]O Alarme de Fusão pode ocorrer após vencer uma batalha[clr 27] no[n]Metaverso. Durante um alarme, o Velvet Room[n] ficará vermelho e os resultados da execução serão diferentes.[n][w][e]

[msg TUTORIAL_MSG02 [Alarme de Fusão]]
[s]Personas ganharão [clr 2]mais valores estatísticos[clr 27], [clr 2]diferentes[n]habilidades[clr 27] e [clr 2]max slots de herança de habilidades[clr 27]. Usar[n]guilhotina, cadeira elétrica ou [clr 2]o mesmo método de execução[n]várias vezes causará um acidente[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Alarme de Fusão]]
[s]Pode ocorrer um acidente se você usar a Persona que[n]foi criada durante o alarme como material. Mas,[n]há uma chance de que os valores estatísticos possam aumentar[n]ainda mais.[n][w][e]

[msg TUTORIAL_MSG04 [Alarme de Fusão]]
[s]Quando ocorrer um acidente, você será avisado para sair.[n]O alarme também terminará se você sair após uma fusão.[n]Você pode [clr 2]falar com os Guardiões para parar o alarme[n]sem fusão[clr 27].[n][w][e]

