[msg TUTORIAL_MSG01 [O Começo de Tudo]]
[s][f 4 2] é considerado culpado de um crime que[n]não cometeu e acaba com ficha criminal.[n]Ele é enviado a Tóquio para cumprir sua liberdade condicional[n]sob custódia de [clr 2]Sojiro Sakura[clr 27] , um conhecido de seus pais.[n][w][e]

[msg TUTORIAL_MSG02 [O Começo de Tudo]]
[s][f 4 2]ele sonha com um homem chamado Igor e[n]aprende que deve se rebelar contra um destino de destruição.[n]Ele também conhece duas misteriosas irmãs gêmeas, que[n]ordenam que ele busque sua [clr 2]reabilitação[clr 27] .[n][w][e]

[msg TUTORIAL_MSG03 [O Começo de Tudo]]
[s]Em sua primeira manhã na Shujin Academy, [f 4 2][n] ele conhece Ryuji Sakamoto. Os dois se aventuram em um estranho castelo, onde um cara que se autodenomina rei quase os mata.[n][w][e]

[msg TUTORIAL_MSG04 [O Começo de Tudo]]
[s]Felizmente, a Persona de [f 4 2] desperta e,[n] graças à ajuda de Morgana, os três conseguem escapar[n] do castelo.[n][w][e]

