[msg TUTORIAL_MSG01 [Girar a Câmera]]
[s]Se você usar [clr 2][f 1 10 45][clr 27], poderá girar a câmera.[n]Ao pressionar [clr 2][f 1 10 70][clr 27] ou [clr 2] [f 1 10 59] [clr 27], você pode redefinir[n]a câmera para sua posição padrão.[w][e]

[msg TUTORIAL_MSG02 [Girar a Câmera]]
[s]Você pode ajustar a velocidade e a direção da rotação [n]da câmera no menu [clr 2]Configuração[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Girar a Câmera]]
[s]Gire a câmera para ver a[n]cidade e as pessoas ao seu redor.[n][w][e]

