[msg TUTORIAL_MSG01 [Fabricando ferramentas de Infiltração]]
[s]Com os materiais certos, você pode criar ferramentas[n]de infiltração, que podem ser úteis ao explorar[n]Palácios. Certifique-se de trazer sempre algumas com você.[n][w][e]

[msg TUTORIAL_MSG02 [Fabricando ferramentas de Infiltração]]
[s]Criar ferramentas levará tempo, mas[n]melhore seu [f 4 11 2][clr 26][f 4 12 2][clr 27].[n]Cada vez que aumentar,[n]você poderá criar uma ferramenta adicional.[n][w][e]

[msg TUTORIAL_MSG03 [Fabricando ferramentas de Infiltração]]
[s]Durante o [clr 2]mau tempo[clr 27], você pode se concentrar[n]mais e criar uma ferramenta adicional.[n]Visite quantas lojas puder para encontrar novos materiais.[n][w][e]

