[msg TUTORIAL_MSG01 [Como usar o Especial]]
[s]O [clr 2]Especial[clr 27], é um combo de ataque entre dois membros do grupo,[n]ele agora está desbloqueado.[n][w][e]

[msg TUTORIAL_MSG02 [Como usar o Especial]]
[s]O Especial é ativado no início do turno de um membro do grupo.[clr 2][n]É um ataque poderoso que só pode ser usado neste momento[clr 27],[n]e não consumirá HP ou SP.[n][w][e]

[msg TUTORIAL_MSG03 [Como usar o Especial]]
[s]Você pode se usar pressionando [clr 2][f 1 10 64][clr 27] quando o[n]respectivo ícone aparecer.[n][w][e]

