[msg TUTORIAL_MSG01 [Il sesto colpo: Sae]]
[s]Os Phantom Thieves são culpados pela morte de[n] Okumura e sua popularidade despenca. A[n]polícia então colocou uma [clr 2]recompensa por suas cabeças[clr 27][n]de até 30 milhões de ienes.[n][w][e]

[msg TUTORIAL_MSG02 [Il sesto colpo: Sae]]
[s]Apesar de sua oposição franca, Akechi[n]afirma que os Phantom Thieves não são culpados[n]da morte de Okumura e insinua que conhece[n]o verdadeiro perpetrador...[n][w][e]

[msg TUTORIAL_MSG03 [Il sesto colpo: Sae]]
[s]Os Phantom Thieves ligam para Akechi na esperança de[n] limpar seu nome, mas ele os força a ajudá-lo em seu plano para despertar o coração de[n] Sae.[n][w][e]

