[msg TUTORIAL_MSG01 [Estudando na biblioteca]]
[s]Quando você estudar na biblioteca, o tempo vai passar, mas[n]você vai melhorar seu [f 4 11 0][clr 26][f 4 12 0][clr 27]. Além disso, em[n][clr 2]mau tempo[clr 27] sua capacidade de concentração aumentará[n]e seu [f 4 11 0][clr 26][f 4 12 0][clr 27] melhorará ainda mais .[n][w][e]

[msg TUTORIAL_MSG02 [Estudando na biblioteca]]
[s]Às vezes, você ouvirá outros alunos falando sobre você.[n]Quando isso acontecer, você perderá a concentração e sua[n][f 4 11 0][clr 26][f 4 12 0][clr 27] pode [clr 2] não aumentar muito[clr 27],[n]mas em troca seu [f 4 11 3][clr 26][f 4 12 3][clr 27] aumentará um pouco.[n][w][e]

