[msg TUTORIAL_MSG01 [Locais dos Confidentes]]
[s]Quando você navega no mapa ferroviário, um ícone de bilhete[n]pode aparecer próximo ao nome de uma[n]estação. Isso significa que naquela área[n] pode haver um ou mais Confidentes.[n][w][e]

[msg TUTORIAL_MSG02 [Locais dos Confidentes]]
[s]Você pode ver os nomes dos Confidants e informações[n]sobre a área pressionando [clr 2][f 1 10 33][clr 27]. Se ninguém lhe enviou[n]um convite para sair, tente verificar quem está por perto.[n][w][e]

