[msg TUTORIAL_MSG01 [Il settimo colpo: Shido]]
[s]Depois de enganar Akechi, [f 4 2] se esconde[n] para evitar que Masayoshi Shido descubra que ele[n] está vivo e bem.[n][w][e]

[msg TUTORIAL_MSG02 [Il settimo colpo: Shido]]
[s]Enquanto isso, a popularidade de Shido dispara.[n][f 4 2] ouve sua voz durante um discurso[n]e se convence de que Shido armou para ele.[n][w][e]

[msg TUTORIAL_MSG03 [Il settimo colpo: Shido]]
[s]Os Phantom Thieves se infiltram no palácio de Shido para despertar seu coração, mas são parados por[n] Akechi, que revela ser o responsável pelas[n] prisões mentais.[n][w][e]

[msg TUTORIAL_MSG04 [Il settimo colpo: Shido]]
[s]Eventualmente, Akechi revela seu plano, mas os Phantom Thieves conseguem dominá-lo e prometem despertar o coração de Shido.[n][w][e]

[msg TUTORIAL_MSG05 [Il settimo colpo: Shido]]
[s]Os Phantom Thieves invadem as telas gigantes do Japão e encenam sua carta de desafio mais louca até agora. Eles anunciam que estão sãos e salvos e acusam[n]Shido. A febre dos Ladrões Fantasmas reacende.[n][w][e]

[msg TUTORIAL_MSG06 [Il settimo colpo: Shido]]
[s]Os Phantom Thieves conseguem derrotar a Shadow[n]of Shido, mas ele, em uma última tentativa desesperada,[n]tenta eliminá-los destruindo seu próprio palácio,[n]falhando miseravelmente.[n][w][e]

