[msg D_TUTORIAL_37_mes01 [Gancho com corrente]]
[s]Graças às aulas com Kasumi,[n][f 4 2] pode usar o [clr 2]Gancho com corrente[clr 27].[n][w][e]

[msg D_TUTORIAL_37_mes02 [Gancho com corrente]]
[s]Usar o gancho permitirá que você ataque[n] uma sombra mais longe do que o normal[n] e inicie uma batalha preventiva.[n][w][e]

[msg D_TUTORIAL_37_mes03 [Gancho com corrente]]
[s]Quando você inicia uma batalha com o Gancho com corrente,[n]os inimigos começarão a luta[n]com Tontura, Confusão ou Medo.[n][w][e]

