[msg TUTORIAL_MSG01 [Confidentes]]
[s][clr 2]Confidentes[clr 27] são pessoas em quem você confia e que [n]compartilha um objetivo semelhante. Você pode encontrar [n]essas pessoas em lugares como a escola [n]ou pela cidade.[n][w][e]

[msg TUTORIAL_MSG02 [Confidentes]]
[s]Tente construir conexões com as pessoas[n]encontrando-as várias vezes, ganhando[n]a confiança delas e provando seu valor.[n][w][e]

[msg TUTORIAL_MSG03 [Confidentes]]
[s]Depois que um vínculo é estabelecido, você pode abrir o[n]menu com [f 1 10 25] e selecionar [clr 2]Confidentes[clr 27][n]para verificar a força do seu vínculo.[n][w][e]

