[msg TUTORIAL_MSG01 [Jogando dardos]]
[s]Jogar dardos vai fazer o tempo passar, mas[n]você pode convidar [clr 2]seus companheiros de equipe[clr 27] para jogar [n]com você. Ao jogar juntos, você fortalecerá seu vínculo com[n]eles e melhorará os efeitos de [clr 2]Corrida de Revezamento[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Jogando dardos]]
[s]Jogar dardos com amigos[n]pode melhorar o revezamento[n]com vários companheiros de equipe.[n][w][e]

[msg TUTORIAL_MSG03 [Jogando dardos]]
[s]Você pode ver o Rank do Passe de Bastão dos membros [n]do seu grupo ao escolher quem você convidará para[n]jogar dardos. Você também pode ver como os membros[n]do seu grupo jogam dardos pressionando [f 1 10 33].[n][w][e]

[msg TUTORIAL_MSG04 [Jogando dardos]]
[s]Você também pode jogar dardos sozinho.[n]Você não vai melhorar seus laços com seus companheiros[n]de equipe, mas pode praticar o[n]quanto quiser.[n][w][e]

