[msg TUTORIAL_MSG01 [Scegliere un luogo di incontro]]
[s]Quando você descobre um ponto de encontro, pode[n]viajar até ele com um de seus Confidentes.[n][w][e]

[msg TUTORIAL_MSG02 [Scegliere un luogo di incontro]]
[s]Os locais de encontro podem ser selecionados[n] no mapa. Todo Confidente tem um favorito;[n]lembre-se disso ao visitá-los com um[n]confidente.[n][w][e]

[msg TUTORIAL_MSG03 [Scegliere un luogo di incontro]]
[s]Dependendo do dia e do clima,[n]você não poderá visitar determinados lugares,[n]cuidado com ambos.[n][w][e]

