[msg TUTORIAL_MSG01 [Características]]
[s]Cada Persona tem suas [clr 2]Características[clr 27] específicas. Cada[n]característica é única. Algumas reduzem o custo de uma[n]habilidade ou aumentam o poder de um[n]atributo específico.[n][w][e]

[msg TUTORIAL_MSG02 [Características]]
[s]Existem vários benefícios associados ao uso da [clr 2]Características[clr 27][n]em batalha. Certifique-se de levar em conta quais ações[n]utilizarão melhor as [clr 2]Características[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Características]]
[s]Você pode ver os[clr 2]detalhes das características[clr 27] de uma Persona[n]em sua respectiva tela de estados[n]pressionando [f 1 10 33].[n][w][e]

