[msg TUTORIAL_MSG01 [Implorando pela vida]]
[s]Quando o inimigo está em perigo de morte, ele pode tentar[n]implorar por sua vida, permitindo que você negocie com ele[n]e talvez obtenha uma Persona.[n][w][e]

[msg TUTORIAL_MSG02 [Implorando pela vida]]
[s]A personalidade da Sombra determina a chance de implorar.[n][clr 2]Sombras tímidas[clr 27] são mais propensas a implorar, enquanto[n][clr 2]Sombras excêntricas [clr 27]não imploram com muita frequência.[n][w][e]

