[msg TUTORIAL_MSG01 [Il quarto colpo: Futaba]]
[s]Após o despertar do coração de Kaneshiro,[n] os Phantom Thieves veem sua popularidade[n] disparar. Isso leva a notória rede de[n]hacking chamada [clr 2]Medjed[clr 27] a desafiá-los.[n][w][e]

[msg TUTORIAL_MSG02 [Il quarto colpo: Futaba]]
[s]O desafio deixa o público em êxtase, mas devido ao anonimato de Medjed, os Phantom Thieves não sabem para onde ir. De repente,[n]eles recebem uma mensagem de um certo [clr 2]Alibaba[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Il quarto colpo: Futaba]]
[s]Alibaba se oferece para ajudar os Phantom Thieves[n] a rota Medjed em troca de despertar o[n] coração de outro alvo. Encurralado,[n]a equipe só pode aceitar as condições.[n][w][e]

[msg TUTORIAL_MSG04 [Il quarto colpo: Futaba]]
[s]Na mesma época, [f 4 2] descobre que Sojiro[n] assumiu a custódia de [clr 2]Futaba[clr 27], filha de[n]seu conhecido, [clr 2]Wakaba Isshiki[clr 27].[n][w][e]

[msg TUTORIAL_MSG05 [Il quarto colpo: Futaba]]
[s]Makoto deduz que a própria Futaba é[n] na verdade Alibaba. Percebendo que salvando-a[n]eles poderiam derrotar Medjed, os[n]Phantom Thieves entram em seu palácio.[n][w][e]

[msg TUTORIAL_MSG06 [Il quarto colpo: Futaba]]
[s]Mas, apesar do desejo de Futaba de ter seu coração[n]despertado, uma entidade dentro do[n]Palácio tenta impedi-la: a monstruosa[n]distorção de sua mãe.[n][w][e]

[msg TUTORIAL_MSG07 [Il quarto colpo: Futaba]]
[s]Desgastada em seu precário[n] estado emocional, a Persona de Futaba desperta e ela,[n] junto com os Phantom Thieves, derrota o[n] warp de Wakaba.[n][w][e]

[msg TUTORIAL_MSG08 [Il quarto colpo: Futaba]]
[s]Depois de acordar, Futaba desmonta o site de Medjed[n] e resolve o caso rapidamente.[n]Graças ao despertar de seu coração, ela começou[n]olhar para a realidade.[n][w][e]

