[msg TUTORIAL_MSG01 [Trabalhando no Bar]]
[s]Trabalhar no café vai fazer com que o tempo passe,[n]mas além de você ganhar dinheiro,[n]seu [f 4 11 4][clr 26][f 4 12 4][clr 27] vai melhorar.[n][w][e]

[msg TUTORIAL_MSG02 [Trabalhando no Bar]]
[s]Haverá dias em que o bar estará lotado.[n]Puxar conversa com vários clientes[n]pode melhorar seu [f 4 11 4][clr 26][f 4 12 4][clr 27], como bem como outra[n]estatística sociais, dependendo de com quem você fala.[n][w][e]

