[msg TUTORIAL_MSG01 [Tipos adicionais de ataque técnicos]]
[s]Novos [clr 2]Combos para ataque técnico adicionados[clr 27].[n]Além de PK, agora você pode usar:[n]- [clr 2]Arma de fogo[clr 27], [clr 2]Vento [clr 27] → Confusão[n]- [clr 2]Congelamento[clr 27] → Medo[n][w][e]

[msg TUTORIAL_MSG02 [Tipos adicionais de ataque técnicos]]
[s]- [clr 2]Eletricidade[clr 27] → Amnésia[n]- [clr 2]Raiva[clr 27] → Queima[n]- [clr 2]Maldição[clr 27] → Desespero[n]- [clr 2]Sagrado[clr 27] → Subjugação[n][w][e]

[msg TUTORIAL_MSG03 [Tipos adicionais de ataque técnicos]]
[s]Fictício[n][w][e]

