[msg TUTORIAL_MSG01 [O que fazer a seguir]]
[s]Se você tiver algum tempo livre e não souber[n]o que fazer, pressione [f 1 10 66] para abrir[n]o [clr 2]comando de ajuda[clr 27] e veja o que[n]você pode fazer e quem você pode encontrar.[n][w][e]

[msg TUTORIAL_MSG02 [O que fazer a seguir]]
[s]Se as [clr 2]funções de internet estiverem LIGADAS[clr 27], você pode usar [f 1 10 42][n]para visualizar o [clr 2]Registro de atividades[clr 27].[n]Isso permitirá que você veja o que os outros jogadores[n]fizeram neste dia no calendário.[n][w][e]

[msg TUTORIAL_MSG03 [O que fazer a seguir]]
[s]O [clr 2]Registro de atividades[clr 27] é uma ferramenta[n]que vai te ajudar nas horas vagas.[n]Leia mais no [clr 2]Tutorial[clr 27].[n][w][e]

