[msg TUTORIAL_MSG01 [Acessórios com habilidade]]
[s]Alguns acessórios [clr 2]permitem que você use[n]uma habilidade[clr 27]. Quando um membro do grupo está[n]equipado com um deles, ele tem a chance[n]de usar a respectiva habilidade.[n][w][e]

[msg TUTORIAL_MSG02 [Acessórios com habilidade]]
[s]Para visualizar os detalhes de um acessório,[clr 27][n]abra o menu com [f 1 10 25], vá para Equipamento[n]e pressione [f 1 10 56].[n][w][e]

