[msg D_TUTORIAL_23_mes01 [O Ceifador]]
[s]Se você passar muito tempo em uma área de Mementos,[n]uma Sombra assustadora, chamada [clr 2]O Ceifador[clr 27],[n]pode aparecer.[n][w][e]

[msg D_TUTORIAL_23_mes02 [O Ceifador]]
[s]O Ceifador é muito poderoso: [clr 2]é melhor não[n]envolvê-lo em combate[clr 27]. Se você ouvir o [clr 2]barulho[n]das correntes[clr 27], saia da área imediatamente.[n][w][e]

