[msg TUTORIAL_MSG01 [Variações de Técnicas]]
[s][clr 2]Ataques Técnicos[clr 27] ocorrerão durante estas[n][clr 2]combinações[clr 27]: - [clr 2]Vento, Nuclear[clr 27] → Queimar[n]- [clr 2]Físico, Nuclear[clr 27] → Congelado[n]- [clr 2]Físico, Arma, Nuclear[clr 27] → Eletrocutado[n][w][e]

[msg TUTORIAL_MSG02 [Variações de Técnicas]]
[s]- Tonto, Sono → [clr 2]Qualquer tipo de dano[clr 27][n]- Confusão, Medo, Raiva, Desespero, Lavagem cerebral,[n]Esquecer → [clr 2]Telecinesia[clr 27][n][w][e]

