[msg TUTORIAL_MSG01 [Passe de Bastão]]
[s]Agora você pode passar o bastão para mais de um [n]membro do grupo.[n][w][e]

[msg TUTORIAL_MSG02 [Passe de Bastão]]
[s]O destinatário do Bastão terá seu poder de ataque e[n]capacidade de cura aumentados. Se eles repassarem [n]novamente, as estatísticas dos membros do [n]grupo também aumentarão.[n][w][e]

[msg TUTORIAL_MSG03 [Passe de Bastão]]
[s]Ao envolver todos os 4 membros do grupo no Passe de bastão,[n]o último membro pode usar uma habilidade sem[n]consumir HP ou SP.[n][w][e]

[msg TUTORIAL_MSG04 [Passe de Bastão]]
[s]Envolva outro membro do grupo pressionando [clr 2][f 1 10 55][clr 27].[n][w][e]

