[msg TUTORIAL_MSG01 [Ataques especiais e combinações]]
[s]Ataques Especial tem mais chances de acontecer você usar o[n][clr 2]Passe de Bastão com o [clr 27][clr 2][f 4 2] ou outro[n]membro do grupo em dificuldade[clr 27], ou[n]quando [clr 2]um inimigo está perto de ser derrotado[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Ataques especiais e combinações]]
[s]Inicialmente, o ataque especial só será ativado com [n]Ann e Morgana. No entanto, você pode obter outras[n]combinações à medida que avança na historia.[n][w][e]

[msg TUTORIAL_MSG03 [Ataques especiais e combinações]]
[s]O Ataque especial pode ser ativado mesmo se o outro [n]membro do grupo for um reserva. Você pode ver as várias [n]combinações em [clr 2]Estatísticas[clr 27],[n]no menu [f 1 10 25].[n][w][e]

