[msg TUTORIAL_MSG01 [Ataques com armas de fogo]]
[s]Os ataques com armas de fogo são considerados uma[n]"habilidade com arma". [clr 2]Pressione [f 1 10 40]para preparar sua arma[clr 27],[n]depois [clr 2][f 1 10 21] para atirar[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Ataques com armas de fogo]]
[s]Você pode continuar atirando até ficar sem[n]munição. Você também pode [clr 2]trocar de alvos[n]entre os tiros com [f 1 10 41][clr 27].[n][w][e]

