[msg TUTORIAL_MSG01 [Frenético]]
[s]Se você pressionar [clr 2][f 1 10 60][clr 27] durante a batalha, seu grupo fará[n]ataques corpo a corpo. Isso é chamado de modo [clr 2]Frenético[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Frenético]]
[s]Durante um modo Frenético, a batalha será mais rápida e você[n]não terá que emitir nenhuma ordem. O modo Frenético pode[n]ser cancelado pressionando [clr 2][f 1 10 70][clr 27].[n][w][e]

