[msg TUTORIAL_MSG01 [Usando a lagoa de pesca]]
[s]Pescar vai fazer com que o tempo passe, mas os pontos[n]ganhos com a pesca podem[n]ser trocados por prêmios. Além disso, seu[n][f 4 11 2][clr 26][f 4 12 2][clr 27] vai melhorar.[n][w][e]

[msg TUTORIAL_MSG02 [Usando a lagoa de pesca]]
[s]Os peixes capturados são categorizados de acordo com[n]o tamanho e espécie.[n]Pesque peixes maiores e mais raros para ganhar mais pontos.[n][w][e]

[msg TUTORIAL_MSG03 [Usando a lagoa de pesca]]
[s]Conforme [f 4 11 2][clr 26][f 4 12 2][clr 27] aumenta, o número[n]de vezes que você pode pescar por visita também aumentará.[n]Tente aumentar seu [f 4 11 2][clr 26][f 4 12 2][clr 27] para que você possa[n]pescar com mais frequência.[n][w][e]

