[msg TUTORIAL_MSG01 [Usare le abilità]]
[s]Durante o seu turno, você pode usar[n]habilidades pressionando [clr 2][f 1 10 26][clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Usare le abilità]]
[s]Depois de selecionar a habilidade desejada,[n]você pode escolher o alvo para[n]acertar.[n][w][e]

[msg TUTORIAL_MSG03 [Usare le abilità]]
[s]Usar uma habilidade requer uma certa[n]quantidade de HP ou SP.[n][w][e]

