[msg TUTORIAL_MSG01 [Conhecimentos da Sombra]]
[s]Agora você pode usar [clr 2]Conhecimentos da Sombra[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Conhecimentos da Sombra]]
[s]Ao selecionar um alvo na batalha,[n]você pode ver quais ataques são[n][clr 2]anulados, refletidos ou absorvidos[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Conhecimentos da Sombra]]
[s]No entanto, se as afinidades do inimigo[n]tiverem um "?", [clr 2]o status dos ataques não é mostrado[clr 27].[n][w][e]

