[msg TUTORIAL_MSG01 [Lutando contra inimigos ferozes]]
[s]Inimigos ferozes vagam pelos Palácios cercados por uma[n]aura vermelha. O nível desses oponentes tende a ser maior do que[n]o das Sombras próximas.[n][w][e]

[msg TUTORIAL_MSG02 [Lutando contra inimigos ferozes]]
[s]Para negociar com um inimigo feroz, você deve danificá-lo[n]até que ele mude [clr 2]sua posição de combate[clr 27].[n]Nesse ponto, você pode prosseguir.[n][w][e]

[msg TUTORIAL_MSG03 [Lutando contra inimigos ferozes]]
[s]Se você não conseguir derrotar um inimigo feroz,[n]você sempre pode fugir. Pressione [f 1 10 50] e selecione "ESCAPAR"[n]na opções "Mudança de táticas".[n][w][e]

