[msg TUTORIAL_MSG01 [Ritorno alla normalità?]]
[s]Os Phantom Thieves, estimulados pelas esperanças do povo,[n]derrotam o deus maligno Yaldabaoth.[n]Com o caso de Shido em apuros, [clr 2]Akechi[n]retorna[clr 27] e decide armar .[n][w][e]

[msg TUTORIAL_MSG02 [Ritorno alla normalità?]]
[s]Após a última missão dos Ladrões Fantasmas, Morgana,[n]que todos pensavam estar desaparecida, [clr 2]reaparece em forma de gato[clr 27].[n]Sae informa [f 4 2] sobre o caso de [clr 2] Shido [clr 27] e[n]notifique-o [clr 2]que ele foi inocentado de todas as acusações[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Ritorno alla normalità?]]
[s]Mas, quando o novo ano começa, algo[n]estranho acontece: a falecida mãe de Futaba, [clr 2]Wakaba Isshiki,[n]ainda está viva[clr 27] e [clr 2]Morgana agora é humana.[clr 27] Ninguém,[n] no entanto, abriga suspeitas, exceto [f 4 2].[n][w][e]

[msg TUTORIAL_MSG04 [Ritorno alla normalità?]]
[s]É então que Akechi reaparece. Inocentado[n]das acusações e liberado, como [f 4 2], ele também nota[n]a estranheza da situação. Para descobrir o que está acontecendo, os dois decidem trabalhar juntos.[n][w][e]

[msg TUTORIAL_MSG05 [Ritorno alla normalità?]]
[s][f 4 2]Recebe uma ligação de [clr 2]Kasumi[clr 27].[n]A garota os informa que o [clr 2]Palácio[n]em que eles entraram anteriormente reapareceu[clr 27].[n]É onde eles os três portanto, decida se encontrar.[n][w][e]

[msg TUTORIAL_MSG06 [Ritorno alla normalità?]]
[s]O líder dos Phantom Thieves, aquele que os traiu e a garota que se recusou a fazer parte deles entram no misterioso Palácio para esclarecer a situação anômala.[n][w][e]

