[msg TUTORIAL_MSG01 [Comandos de assistência ]]
[s]Quando você está perdido, os comandos de assistência podem[n]fornecer recomendações, com base em suas condições atuais,[n]para atividades a serem realizadas e confidentes para ver.[n][w][e]

[msg TUTORIAL_MSG02 [Comandos de assistência ]]
[s]Pressione [f 1 10 29] para abrir o assitncia de confidente para ver qual[n]confidente é recomendado para aquela hora do dia.[n][w][e]

[msg TUTORIAL_MSG03 [Comandos de assistência ]]
[s]Pressione [f 1 10 24] para abrir o Status Assist e ver qual[n]atividade diária é recomendada para você.[n][w][e]

[msg TUTORIAL_MSG04 [Comandos de assistência ]]
[s]Pressione [f 1 10 37] para reunir todos no esconderijo. Além disso,[n]se você ativar as funções de rede, poderá usar[n][f 1 10 42] para ver o [clr 2]Registro de atividades[clr 27] de outros jogadores.[n][w][e]

[msg TUTORIAL_MSG04_Fiber_NX [Comandos de assistência ]]
[s]Pressione [f 1 10 37] para reunir todos no esconderijo. Além disso,[n]se você ativar as funções de rede, poderá usar[n][f 1 10 42] para ver o [clr 2]Registro de atividades[clr 27] de outros jogadores.[n][w][e]

[msg TUTORIAL_MSG04_Fiber_PS5 [Comandos de assistência ]]
[s]Pressione [f 1 10 37] para reunir todos no esconderijo. Além disso,[n]se você ativar as funções de rede, poderá usar[n][f 1 10 42] para ver o [clr 2]Registro de atividades[clr 27] de outros jogadores.[n][w][e]

[msg TUTORIAL_MSG04_Fiber_Xbo [Comandos de assistência ]]
[s]Pressione [f 1 10 37] para reunir todos no esconderijo. Além disso,[n]se você ativar as funções de rede, poderá usar[n][f 1 10 42] para ver o [clr 2]Registro de atividades[clr 27] de outros jogadores.[n][w][e]

[msg TUTORIAL_MSG04_Fiber_Ste [Comandos de assistência ]]
[s]Pressione [f 1 10 37] para reunir todos no esconderijo. Além disso,[n]se você ativar as funções de rede, poderá usar[n][f 1 10 42] para ver o [clr 2]Registro de atividades[clr 27] de outros jogadores.[n][w][e]

