[msg TUTORIAL_MSG01 [Passe de Bastão]]
[s]Agora você pode realizar um Passe de bastão pressionando[n][clr 2][f 1 10 55][clr 27] após acionar um 1 More.[n][w][e]

[msg TUTORIAL_MSG02 [Passe de Bastão]]
[s]Isso permite que você passe a ação[n]garantida por um 1 a mais para um companheiro de equipe,[n]cuja força aumentará bastante.[n][w][e]

[msg TUTORIAL_MSG03 [Passe de Bastão]]
[s]Você pode executar um Relay com [clr 2]qualquer pessoa[clr 27][n]capaz de agir. Use-o com sabedoria.[n][w][e]

