[msg TUTORIAL_MSG01 [Usando o banheiro público]]
[s]O banho público vai melhorar seu [f 4 11 1][clr 26][f 4 12 1][clr 27],[n]mas usá-lo vai passar o tempo.[n]A taxa de entrada é de 500 ienes.[n][w][e]

[msg TUTORIAL_MSG02 [Usando o banheiro público]]
[s]Os benefícios do banho público variam[n]dependendo do dia e do clima. Vá lá de vez em quando para[n]descobrir o que ele tem a oferecer.[n][w][e]

