[msg TUTORIAL_MSG01 [Crepe nella difesa nemica]]
[s]Ataques com armas de fogo não infligem[n]acertos críticos, mas enfraquecem a defesa do[n]inimigo aumentando a frequência de críticos[n]com outros ataques.[n][w][e]

[msg TUTORIAL_MSG02 [Crepe nella difesa nemica]]
[s]Quanto maior o seu poder de ataque, mais[n]provável é que você quebre a defesa inimiga.[n]As rachaduras desaparecem após um acerto crítico.[n][w][e]

