[msg TUTORIAL_MSG01 [Habilidades de Confidentes]]
[s]As pessoas com quem você se relaciona[n]têm [clr 2]Habilidades espaciais[clr 27] de confidente.[n][w][e]

[msg TUTORIAL_MSG02 [Habilidades de Confidentes]]
[s]A [clr 2]Classificação de Confidentes[clr 27] indica o quanto você[n]confia em alguém. À medida que a classificação aumenta, novas[n]habilidades são desbloqueadas.[n][w][e]

[msg TUTORIAL_MSG03 [Habilidades de Confidentes]]
[s]Pressione [f 1 10 25] para abrir o menu e selecione[n][clr 2]Confidente[clr 27]. A partir daí, você pode verificar no arcano,[n]a classificação e as habilidades de cada confidente.[n][w][e]

