[msg TUTORIAL_MSG01 [Como jogar Dardos]]
[s]Use o controle sem fio para mirar e segure [f 1 10 57][n]para confirmar onde deseja lançar o dardo.[n]Você também pode pressionar [f 1 10 30] para{ 0A}redefinir a área de destino.[n][w][e]

[msg TUTORIAL_MSG02 [Como jogar Dardos]]
[s]Agite o controle para disparar o dardo[n]em direção à [clr 2]ao alvo[clr 27].[n]Tenha cuidado para não soltar o controle. { 0A}[w][e]

[msg TUTORIAL_MSG01_Fiber_NX [Como jogar Dardos]]
[s]Incline o Joy-Con™ para mirar.[n][w][e]

[msg TUTORIAL_MSG01_Fiber_PS5 [Como jogar Dardos]]
[s]Use o controle sem fio para mirar.[n][w][e]

[msg TUTORIAL_MSG01_Fiber_Xbo [Como jogar Dardos]]
[s]Use [f 1 10 71] para mover o dardo e [f 1 10 72] para girá-lo[n]e mirar.[n][w][e]

[msg TUTORIAL_MSG01_Fiber_Ste [Como jogar Dardos]]
[s]Use [f 1 10 71] ou o mouse para mover o dardo e [n][f 1 10 72] para girá-lo e mirar.[n][w]{00 }[e]

[msg TUTORIAL_MSG02_Fiber_NX [Como jogar Dardos]]
[s]Segure [f 1 10 57][n]para confirmar onde deseja lançar o dardo.[n]Você também pode pressionar [f 1 10 30] para redefinir a área alvo.[n][w][e]

[msg TUTORIAL_MSG02_Fiber_PS5 [Como jogar Dardos]]
[s]Segure [f 1 10 57][n]para confirmar onde deseja lançar o dardo.[n]Você também pode pressionar [f 1 10 30] para redefinir a área alvo.[n][w][e]

[msg TUTORIAL_MSG02_Fiber_Xbo [Como jogar Dardos]]
[s]Segure [f 1 10 57] para decidir onde lançar o dardo.[n]Se sua mira se mover, você pode redefini-la com [f 1 10 30].[n][w][e]

[msg TUTORIAL_MSG02_Fiber_Ste [Como jogar Dardos]]
[s]Segure [f 1 10 57] clique com o botão direito[n]para decidir onde lançar o dardo.[n]Se sua mira se mover, você pode redefini-la com [f 1 10 30] .[n][w][e]

[msg TUTORIAL_MSG03_Fiber_NX [Como jogar Dardos]]
[s]Segure [f 1 10 57] e agite o Joy-Con™ para atirar o [n]dardo na [clr 2]área alvo[clr 27]. [n]Tenha cuidado para não soltar o Joy-Con™.[n][w][e]

[msg TUTORIAL_MSG03_Fiber_PS5 [Como jogar Dardos]]
[s]Agite o controle para atirar o dardo na [n][clr 2]área alvo[clr 27]. Tenha cuidado para não soltar [n]o controlador.[n][w][e]

[msg TUTORIAL_MSG03_Fiber_Xbo [Como jogar Dardos]]
[s]Pressione [f 1 10 73] para lançar o dardo em direção[n][clr 2]da área alvo[clr 27].[n][w][e]

[msg TUTORIAL_MSG03_Steam [Como jogar Dardos]]
[s]Pressione [f 1 10 73] para lançar o dardo em direção[n][clr 2]da área alvo[clr 27].[n][w][e]

[msg TUTORIAL_MSG01_1_NX [Regras para jogar Dardos]]
[s]Você pode mirar inclinando o Joy-Con™.[n][f 1 10 22] para lançar o dardo.[n][w][e]

[msg TUTORIAL_MSG01_1_Fiber_P [Regras para jogar Dardos]]
[s]Você pode mirar inclinando o controle.[n][f 1 10 22] para lançar o dardo.[n][w][e]

[msg TUTORIAL_MSG01_1_Fiber_X [Regras para jogar Dardos]]
[s]Você pode mirar inclinando o controle.[n][f 1 10 22] para lançar o dardo.[n][w][e]

[msg TUTORIAL_MSG01_1_Steam [Regras para jogar Dardos]]
[s]Você pode mirar inclinando o controle.[n][f 1 10 22] para lançar o dardo.[n][w][e]

