[msg TUTORIAL_MSG01 [Trabalho na floricultura]]
[s]Trabalhar na floricultura vai fazer com que o tempo passe,[n]mas além de você ganhar dinheiro,[n]seu [f 4 11 4][clr 26][f 4 12 4][clr 27] vai melhorar.[n][w][e]

[msg TUTORIAL_MSG02 [Trabalho na floricultura]]
[s]Às vezes, você receberá [clr 2]um pedido de buquê[clr 27]. Tente fazer de[n]acordo com os desejos do cliente. Se você for bem-sucedido,[n]poderá ganhar mais dinheiro do que o normal. O[n][f 4 11 4][clr 26][f 4 12 4][clr 27] também pode melhorar mais do que o normal.[n][w][e]

