[msg TUTORIAL_MSG01 [Visitando restaurantes]]
[s]Estudar fará com que o tempo passe, mas melhorará[n]seu [f 4 11 0][clr 26][f 4 12 0][clr 27]. Além disso, se você comer, você[n]poderá melhorar seu [f 4 11 3][clr 26][f 4 12 3][clr 27] também.[n][w][e]

[msg TUTORIAL_MSG02 [Visitando restaurantes]]
[s]O cardápio varia de acordo com a estação. Em dias[n]de [clr 2]mau tempo[clr 27] você poderá se concentrar[n]e aumentar seu [f 4 11 0][clr 26][f 4 12 0][clr 27] mais que o habitual.[n][w][e]

