[msg TUTORIAL_MSG01 [La fine dei Ladri Fantasma...?]]
[s]Uma figura vestida de preto se esgueira por[n] um cassino extravagante, levando consigo[n] um tesouro extraordinário.[n][w][e]

[msg TUTORIAL_MSG02 [La fine dei Ladri Fantasma...?]]
[s]Guiado por seus companheiros, o ladrão mascarado se livra de alguns monstros bizarros enquanto tenta escapar do cassino.[n][w][e]

[msg TUTORIAL_MSG03 [La fine dei Ladri Fantasma...?]]
[s]Infelizmente, o ladrão está encurralado.[n]Ele tenta fugir pulando por uma[n]janela, mas encontra a polícia esperando por ele[n]do lado de fora e é capturado...[n][w][e]

[msg TUTORIAL_MSG04 [La fine dei Ladri Fantasma...?]]
[s]Em uma sala de interrogatório escura, um menino[n] - o ladrão mascarado - é interrogado[n] por vários homens.[n][w][e]

[msg TUTORIAL_MSG05 [La fine dei Ladri Fantasma...?]]
[s]Depois de ficar chateado, ele[n]é obrigado a assinar uma confissão ambígua[n]com apenas uma coisa: seu[n]nome, [clr 2][f 4 3][clr 27].[n][w][e]

[msg TUTORIAL_MSG06 [La fine dei Ladri Fantasma...?]]
[s]Uma mulher entra na sala de interrogatório. Ele[n] se apresenta como Sae Niijima, um promotor[n] encarregado de resolver um caso tão complicado[n] quanto bizarro.[n][w][e]

[msg TUTORIAL_MSG07 [La fine dei Ladri Fantasma...?]]
[s]Sae pergunta a ele o significado de "outro mundo"[n] e "roubar corações". [f 4 2], sob a influência de[n]narcóticos, conta a ela como sua vida[n]o levou a esse ponto...[n][w][e]

[msg TUTORIAL_MSG08 [La fine dei Ladri Fantasma...?]]
[s]Sua memória volta para abril,[n]a antes de se tornar um Ladrão Fantasma...[n][w][e]

