[msg TUTORIAL_MSG01 [Regras do jogo de dardos]]
[s]O objetivo de [clr 2]'01[clr 27] é diminuir sua pontuação para [clr 2]0[clr 27].[n]Pressione [f 1 10 33] para verificar os valores em cada área e [n]observe as melhores pontuações usando três dardos por rodada.[n][w][e]

[msg TUTORIAL_MSG02 [Regras do jogo de dardos]]
[s]Um [clr 2]Bust[clr 27] é quando sua pontuação fica abaixo de 0. A[n]rodada terminará e a pontuação obtida será[n][clr 2]anulada[clr 27]. Fique atento ao seu total de pontos atual.[n][w][e]

[msg TUTORIAL_MSG03 [Regras do jogo de dardos]]
[s]Quando você chegar perto de 0, poderá ver como[n]consegue os pontos necessários para fazer [clr 2]"Checkout"[clr 27].[n]Tenha cuidado e aproveite essa possibilidade.[n][w][e]

[msg TUTORIAL_MSG04 [Regras do jogo de dardos]]
[s]Ao jogar dardos, sua habilidade será determinada[n]pelos desafios. Pressione [f 1 10 46] para ver os requisitos.[n]Tente se tornar um campeão de dardos![n][w][e]

