[msg TUTORIAL_MSG01 [Guilda dos Ladrões]]
[s]Você pode receber ajuda de aliados através da [clr 2]Guilda[n]dos Ladrões[clr 27]. Isso está disponível ao se infiltrar no[n]Metaverso enquanto estiver conectado online.[n][w][e]

[msg TUTORIAL_MSG02 [Guilda dos Ladrões]]
[s]Devido à sua eficácia em lidar com muitas[n]situações desesperadas, você só pode solicitar a ajuda[n]da Guilda dos Ladrões um número limitado de vezes.[n][w][e]

[msg TUTORIAL_MSG03 [Guilda dos Ladrões]]
[s]Não há desvantagens em obter ajuda, então não se preocupe[n]quando tiver com problemas.[n][w][e]

