[msg TUTORIAL_MSG01 [La risalita, parte 2]]
[s]A [clr 2]ruína[clr 27] que Igor lhe contou em abril[n]parece ter finalmente se manifestado.[n][w][e]

[msg TUTORIAL_MSG02 [La risalita, parte 2]]
[s]Exceto que [f 4 2] não está morto. Sua[n]"morte" foi uma farsa bem elaborada.[n][w][e]

[msg TUTORIAL_MSG03 [La risalita, parte 2]]
[s]Graças a um bug no telefone, os Phantom Thieves[n]descobrem que Akechi é um traidor, mas[n]eles ainda aceitam seu plano, já que a pessoa para quem ele trabalhava poderia encobrir um assassinato.[n][w][e]

[msg TUTORIAL_MSG04 [La risalita, parte 2]]
[s]Eles devem ser capazes de prevenir[n] o assassinato de [f 4 2] e desmascarar Akechi ao mesmo tempo...[n][w][e]

[msg TUTORIAL_MSG05 [La risalita, parte 2]]
[s]O plano é atrair Akechi para a[n] delegacia de polícia não distorcida fora do Sae Palace.[n] Lá, ele supostamente matou uma falsa cognição de[n] [f 4 2], acreditando que havia conseguido.[n][w][e]

[msg TUTORIAL_MSG06 [La risalita, parte 2]]
[s]Lá dentro, a delegacia de polícia é[n]indistinguível da real, então qualquer um[n]que fosse trazido para lá nunca[n]saberia a diferença.[n][w][e]

[msg TUTORIAL_MSG07 [La risalita, parte 2]]
[s]Graças ao telefone de [f 4 2], deixado em[n] por Sae após o interrogatório, Futaba supostamente ativou[n] remotamente o Meta-Nav e levou Akechi a matar[n] o falso [f 4 2].[n][w][e]

[msg TUTORIAL_MSG08 [La risalita, parte 2]]
[s]Através de Akechi, eles descobrem a identidade de quem estava[n]realmente puxando todos os pauzinhos: [clr 2]Masayoshi Shido[clr 27],[n]que havia usado Akechi para eliminar[n]oponentes políticos.[n][w][e]

[msg TUTORIAL_MSG09 [La risalita, parte 2]]
[s][clr 2]O diretor de Shujin[clr 27], [clr 2]Okumura[clr 27] e até[n]o [clr 2]Diretor da UIS[clr 27] tinham laços sombrios[n]com Shido. Com a verdade revelada, o esquadrão[n] se concentra em destruir Shido.[n][w][e]

