[msg TUTORIAL_MSG01 [Il secondo colpo: Madarame]]
[s]Um dia, os Phantom Thieves encontram[n][clr 2]Yusuke Kitagawa[clr 27], que afirma ser o protegido[n]do grande artista japonês [clr 2]Ichiryusai Madarame[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Il secondo colpo: Madarame]]
[s]Depois de descobrir que Madarame tem[n] um palácio próprio, eles tentam explorar a obsessão de[n] Yusuke por Ann para descobrir mais.[n][w][e]

[msg TUTORIAL_MSG03 [Il secondo colpo: Madarame]]
[s]Yusuke, no entanto, defende Madarame com firmeza.[n][w][e]

[msg TUTORIAL_MSG04 [Il secondo colpo: Madarame]]
[s]Os Phantom Thieves encontram [clr 2]Nakanohara[clr 27],[n]um dos ex-alunos de Madarame. Após[n]descobrir o que Madarame está fazendo[n]a Yusuke, os Phantom Thieves decidem intervir.[n][w][e]

[msg TUTORIAL_MSG05 [Il secondo colpo: Madarame]]
[s]Enquanto eles inspecionam o Palácio Madarame em[n] busca por seu Tesouro, Yusuke faz uma[n] aparição inesperada no Palácio e começa a aceitar[n] a verdade sobre seu mestre.[n][w][e]

[msg TUTORIAL_MSG06 [Il secondo colpo: Madarame]]
[s]Logo após confrontar a Sombra de[n]Madarame, Yusuke repudia seu mentor,[n]desperta sua Persona e ajuda os Ladrões Fantasmas a[n]despertar o coração de Madarame.[n][w][e]

[msg TUTORIAL_MSG07 [Il secondo colpo: Madarame]]
[s]Depois, Madarame vai à TV para implorar[n]perdão. Este [clr 2]despertar do coração de alto nível[clr 27][n]leva o público a se convencer[n]da existência dos Phantom Thieves.[n][w][e]

[msg TUTORIAL_MSG08 [Il secondo colpo: Madarame]]
[s]Enquanto isso, um jovem perspicaz e uma garota igualmente espirituosa assistem do lado de fora das especulações sobre os Ladrões Fantasmas.[n][w][e]

