[msg TUTORIAL_MSG01 [Sombras do Desastre]]
[s]Existem Sombras no Metaverso que são chamadas de [n][clr 2]Sombras do Desastre[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Sombras do Desastre]]
[s]As Sombras do Desastre não agirão. No entanto, [clr 2]quando[n]atacadas, elas contra-atacarão e possivelmente executarão[n]um ataque adicional[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Sombras do Desastre]]
[s]Sombra do desastre são difíceis. No entanto, uma vez[n]derrotadas, elas [clr 2]largam um item explosivo[n][clr 27]que danifica as Sombras ao redor.[n][w][e]

[msg TUTORIAL_MSG04 [Sombras do Desastre]]
[s]Quanto mais dano eles recebem quando derrotadas,[n][clr 2]mais danos eles causam as Sombras ao redor[clr 27].[n]Tente cronometrar bem seus ataques![n][w][e]

[msg TUTORIAL_MSG05 [Sombras do Desastre]]
[s]Se uma Sombra do desastre for derrotada com um[n]ataque de reflexo ou Desespero, ela não[n]explode e não derruba nenhum item.[n][w][e]

