[msg TUTORIAL_MSG01 [Desafio do Big Bang Burger]]
[s]Enfrentar o Desafio do Big Bang Burger vai[n]passar o tempo, mas melhorar seu [f 4 11 3][clr 26][f 4 12 3][clr 27].[n]Aceitar o desafio custa dinheiro.[n][w][e]

[msg TUTORIAL_MSG02 [Desafio do Big Bang Burger]]
[s]O desafio é vencido se você conseguir comer[n] todo o Big Bang Burger. Para fazer isso, você[n]precisará de [f 4 11 0][clr 26][f 4 12 0][clr 27], [f 4 11 2][clr 26][f 4 12 2][clr 27][n]e [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Desafio do Big Bang Burger]]
[s]Ganhe e você receberá um prêmio e um [n] aumento em uma estatística diferente de [f 4 11 3][clr 26][f 4 12 3][clr 27]. Vencer[n]ou perder, seu [f 4 11 3][clr 26][f 4 12 3][clr 27] sempre aumentará.[n][w][e]

