[msg TUTORIAL_MSG01 [Trocando de companheiros na batalha]]
[s]A habilidade do Confidente Hifumi Togo [clr 2]Koma Sabaki[clr 27][n]permite que você substitua membros do grupo[n]no meio de uma batalha.[n][w][e]

[msg TUTORIAL_MSG02 [Trocando de companheiros na batalha]]
[s]Durante o turno de [f 4 2], você pode escolher quem[n]substituir pressionando [clr 2][f 1 10 50][clr 27] e selecionando em [clr 2]Grupo[clr 27][n]nos [clr 0]Pedidos[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Trocando de companheiros na batalha]]
[s][clr 2]Substituir um membro do grupo contará como [clr 27][clr 2]uma[n]ação de [f 4 2] para aquele turno.[clr 27][n]Além disso, você não pode substituir um companheiro[n]afetado por um alteração.[n][w][e]

