[msg TUTORIAL_MSG01 [Táticas do grupo]]
[s]Você pode mudar as ações dos membros do seu grupo[n]durante a batalha no [clr 2]atribuindo táticas[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Táticas do grupo]]
[s]Você pode definir um caminho de ação específico para[n]eles seguirem ou optar por controlá-los diretamente.[n][w][e]

[msg TUTORIAL_MSG03 [Táticas do grupo]]
[s]Você pode [clr 2]atribuir táticas[clr 27] acessando [clr 2]Estatísticas[clr 27] no menu[n][f 1 10 25].[n][w][e]

[msg TUTORIAL_MSG04 [Táticas do grupo]]
[s]Você também pode mudar de tática pressionando [clr 2][f 1 10 50][clr 27] na vez de[n][f 4 2] e selecionando [clr 2]Táticas[clr 27] no[n]o menu [clr 2]Pedido[clr 27].[n][w][e]

