[msg TUTORIAL_MSG01 [Personalidade das sombras]]
[s]As Sombras Inimigas têm personalidades que[n]determinam as respostas que preferem. Saber disso[n]será útil para negociações bem sucedidas.[n][w][e]

[msg TUTORIAL_MSG02 [Personalidade das sombras]]
[s][clr 2]brincalhonas[clr 27] apreciam respostas espirituosas, mas[n]desprezam as sérias ou vagas.[n][clr 2]Tímidas[clr 27] gostam de respostas gentis mas odeiam[n]respostas vagas ou brincalhonas.[n][w][e]

[msg TUTORIAL_MSG03 [Personalidade das sombras]]
[s][clr 2]Desonestas[clr 27] apreciam respostas sérias, mas desprezam[n]aquelas que são vagas ou gentis.[n][clr 2]Sombrias[clr 27] gostam de respostas que são vagas, mas odeiam[n]respostas sérias ou divertidas.[n][w][e]

[msg TUTORIAL_MSG04 [Personalidade das sombras]]
[s]Você pode verificar a personalidade de uma Sombra ao[n]selecioná-la na tela Hold Up ou verificando [n]na tela Análise.[n][w][e]

