[msg TUTORIAL_MSG01 [Confirmando Pedidos de Mementos]]
[s]Verifique suas informações sobre um alvo selecionando em[n][clr 2]Exibir solicitações[clr 27] no Hangout ou pressionando[n][f 1 10 25] para visualizar [clr 2]Solicitações[clr 27] no menu principal.[n][w][e]

[msg TUTORIAL_MSG02 [Confirmando Pedidos de Mementos]]
[s]Assim que a informação for confirmada, você pode[n]iniciar a missão selecionando [clr 2]Explorar Mementos[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Confirmando Pedidos de Mementos]]
[s]Mementos podem ser explorados mesmo sem um[n]objetivo, mas o tempo passará como em[n]uma infiltração no Palácio. Tenha cuidado[n]quando o prazo estiver próximo.[n][w][e]

