[msg TUTORIAL_MSG01 [Magnate]]
[s]Reúna a festa para jogar Tycoon. [clr 2]3 partidas[n]forma 1 conjunto[clr 27]. A [clr 2]classificação final[clr 27] é determinada[n]com base nos pontos obtidos em cada partida.[n][w][e]

[msg TUTORIAL_MSG02 [Magnate]]
[s]Você ganhará medalhas P com base na dificuldade e classificação final[n]. Complete desafios para obter[n]mais pontos. Para mais detalhes, consulte [clr 2]Desafios[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Magnate]]
[s]Você encontrará seus resultados em [clr 2]Arquivos[clr 27].[n][w][e]

