[msg D_TUTORIAL_11_mes01 [Escondendo atrás de lugares]]
[s]Se você estiver perto de uma cobertura, pressione [clr 2][f 1 10 22][clr 27] para[n] se ocultar. A partir daí, você pode espreitar[n]para a frente e [clr 2]os inimigos não podem encontrá-lo[clr 27].[n][w][e]

[msg D_TUTORIAL_11_mes02 [Escondendo atrás de lugares]]
[s]Se houver outra cobertura por perto,[n]você pode pressionar [clr 2][f 1 10 22][clr 27] para alcançá-la instantaneamente.[n][w][e]

[msg D_TUTORIAL_11_mes03 [Escondendo atrás de lugares]]
[s]Além disso, se você estiver dentro do alcance de um inimigo,[n]você pode atacá-lo por trás da cobertura[n]para preparar uma [clr 2]emboscada[clr 27].[n][w][e]

[msg D_TUTORIAL_11_mes04 [Escondendo atrás de lugares]]
[s]Aproveite isso para obter uma vantagem.[n]No entanto, saiba que você não pode se proteger[n]se um inimigo já estiver perseguindo você.[n][w][e]

