[msg TUTORIAL_MSG01 [Instinto de Investigador]]
[s]Sempre que [clr 1]Instinto de investigador[clr 27] entra em ação no início[n]de uma batalha, você deduz informações sobre[n]a afinidade de um inimigo.[n][w][e]

[msg TUTORIAL_MSG02 [Instinto de Investigador]]
[s]Ele pode até [clr 2]revelar as fraquezas do inimigo[clr 27]...[n]Verifique a tela de Análise após sua[n]ativação para obter mais informações táticas.[n][w][e]

