[msg TUTORIAL_MSG01 [Afinidades]]
[s]Todas as Personas e Sombras têm suas afinidades.[n][w][e]

[msg TUTORIAL_MSG02 [Afinidades]]
[s]?: Desconhecida, você ainda não atacou.[n]Fraca: Causa grandes quantidades de dano e pode ser derrubada.[n][w][e]

[msg TUTORIAL_MSG03 [Afinidades]]
[s]Resistência: Não sofre muito dano.[n]Cancelar: Não sofre dano.[n]Refletir: Reflete o dano.[n]Absorver: Absorve o dano.[n][w][e]

[msg TUTORIAL_MSG04 [Afinidades]]
[s]Você pode alterar as afinidades de atributos com buffs e[n]habilidades passivas.[n][w][e]

