[msg TUTORIAL_MSG01 [Assistência de seleção de habilidades]]
[s]Se você for capaz de atacar a fraqueza de um inimigo,[n]você pode pressionar [clr 2][f 1 10 52][clr 27] durante a batalha para automaticamente[n]mover o cursor para essa opção.[n][w][e]

[msg TUTORIAL_MSG02 [Assistência de seleção de habilidades]]
[s]Isso deve poupar algum tempo,[n]se você já conhecer a fraqueza do inimigo.[n][w][e]

