[msg TUTORIAL_MSG01 [O registro de atividades]]
[s]Conectando-se online, você pode verificar[n]as ações realizadas por outros jogadores[n]em uma fase específica do mesmo dia.[n][w][e]

[msg TUTORIAL_MSG02 [O registro de atividades]]
[s]Pressione [clr 2][f 1 10 65][clr 27] para ver o[n]log de atividades de outros jogadores. Este recurso[n]não afetará o jogo ou a história.[n][w][e]

[msg TUTORIAL_MSG03 [O registro de atividades]]
[s]Para desativar esse recurso, abra[n]o menu principal com [f 1 10 25], selecione[n][clr 2]Sistema[clr 27] e acesse [clr 2]Configuração[clr 27].[n][w][e]

