[msg TUTORIAL_MSG01 [Personalizza Covo]]
[s]Depois de ter [clr 2]comprado[clr 27][n]itens com P Medals, você poderá colocá-los[n]no Thieves' Den.[n][w][e]

[msg TUTORIAL_MSG02 [Personalizza Covo]]
[s][clr 2]Aliados cognitivos e confidentes[clr 27] vêm[n]para [clr 2]ver objetos e falar sobre eles[clr 27]. Os personagens[n] mudam quando você entra no[n] Covil dos Ladrões ou move objetos.[n][w][e]

[msg TUTORIAL_MSG03 [Personalizza Covo]]
[s]Você pode alterar [clr 2]decorações[clr 27] com base em[n]progresso. O interior do Covo dei Ladri[n]pode mudar de acordo com o mobiliário.[n][w][e]

