[msg TUTORIAL_MSG01 [tipos de equipamentos]]
[s]Na loja de Airsoft você pode comprar réplicas de[n]armas de longo alcance, corpo a corpo,[n]proteções e acessórios.[n][w][e]

[msg TUTORIAL_MSG02 [tipos de equipamentos]]
[s]Armas corpo a corpo aumentam o poder de seus[n]ataques normais, são úteis para derrotar inimigos[n]sem usar habilidades.[n][w][e]

[msg TUTORIAL_MSG03 [tipos de equipamentos]]
[s]Armas de longo alcance aumentam seu poder com[n] armas de fogo. Essas armas causam mais dano do que[n] corpo a corpo e são úteis contra inimigos mais difíceis.[n][w][e]

[msg TUTORIAL_MSG04 [tipos de equipamentos]]
[s]A armadura reduz o dano recebido e é[n]essencial para permanecer mais tempo na batalha.[n]Os acessórios têm vários efeitos, como defesa[n]contra a doenças.[n][w][e]

