[msg TUTORIAL_MSG01 [Jogando Bilhar]]
[s]O tempo vai passar se você jogar bilhar. No entanto, você[n]poderá convidar [clr 2]seus companheiros de equipe[clr 27][n]para jogar com você.[n][w][e]

[msg TUTORIAL_MSG02 [Jogando Bilhar]]
[s]Ao se concentrar, você pode melhorar[n]uma [clr 2]estatística social[clr 27] inesperada. Você também pode aprofundar[n]seu vínculo com os membros de sua equipe.[n][w][e]

