[msg TUTORIAL_MSG01 [Controles de Pesca (Parte 1)]]
[s]Usando [clr 2][f 1 10 43][clr 27], escolha a direção desejada[n] e pressione [clr 2][f 1 10 22][clr 27] para lançar a linha.[n][w][e]

[msg TUTORIAL_MSG02 [Controles de Pesca (Parte 1)]]
[s]A distância alcançada pela linha é determinada[n] pelo indicador de energia. Tente pressionar [clr 2][f 1 10 22][clr 27][n]na hora certa para soltar a isca na frente de[n]um peixe.[n][w][e]

[msg TUTORIAL_MSG03 [Controles de Pesca (Parte 1)]]
[s]Depois de lançar sua linha, espere o peixe[n] morder. Você pode escolher uma isca diferente[n]e lançar novamente pressionando [clr 2][f 1 10 70][clr 27].[n][w][e]

