[msg D_TUTORIAL_30_mes01 [Mudanças de cognição em Mementos]]
[s]Ao coletar selos, você receberá pontos que poderá usar para[n]fazer com que Jose mude sua cognição ambiental.[n][w][e]

[msg D_TUTORIAL_30_mes02 [Mudanças de cognição em Mementos]]
[s]Ao alterar sua cognição, você pode aumentar[n]a quantidade de [clr 2]dinheiro[clr 27], [clr 2]itens[clr 27] ou [clr 2]experiência[clr 27][n]que você pode obter em Lembranças.[n][w][e]

[msg D_TUTORIAL_30_mes03 [Mudanças de cognição em Mementos]]
[s]Você poderá escolher qual [clr 2]efeito aumentar[clr 27][n]ao investir pontos. Use-os com sabedoria para continuar[n]sua exploração.[n][w][e]

[msg D_TUTORIAL_30_mes04 [Mudanças de cognição em Mementos]]
[s]Você pode [clr 2]redefinir[clr 27] pontos investidos usando[n][clr 2]clubes[clr 27]. Porém, quanto mais pontos você investir,[n]mais clubes serão necessários.[n][w][e]

[msg D_TUTORIAL_30_mes05 [Mudanças de cognição em Mementos]]
[s]Para ver a mudança de cognição atual, use [clr 2][f 1 10 53][clr 27][n]para mostrar o mapa principal. Você pode verificar seu[n]status a qualquer momento durante a navegação.[n][w][e]

