[msg TUTORIAL_MSG01 [Tempo livre durante outras aulas]]
[s] Kawakami às vezes lhe dará tempo livre [n] chamando os professores para fora da sala de aula. Use esse[n]tempo para fazer várias coisas, como [clr 2]ler[clr 27][n]ou criar [clr 2]ferramentas de infiltração[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Tempo livre durante outras aulas]]
[s]No entanto, você ganhará [f 4 11 0][clr 26][f 4 12 0][clr 27] ao[n]escolher estudar. Lembre-se dessa[n]compensação.[n][w][e]

