[msg TUTORIAL_MSG01 [Classificação da Passagem de Bastão]]
[s]Quanto mais alto for sua Classificação de Passagem de bastão,[n]mais poderosos serão os efeitos da Passagem de bastão.[n][w][e]

[msg TUTORIAL_MSG02 [Classificação da Passagem de Bastão]]
[s]Posição 1[n]Aumento do dano e recuperação de HP.[n][w][e]

[msg TUTORIAL_MSG03 [Classificação da Passagem de Bastão]]
[s]Posição 2[n]Aumento do dano e recuperação de HP.[n]Cura HP no final da Passagem de bastão.[n][w][e]

[msg TUTORIAL_MSG04 [Classificação da Passagem de Bastão]]
[s]Posição 3[n]Aumento do dano e recuperação de HP.[n]Cura HP no final da passagem de bastão.[n]Recupera SP após Passagem de bastão.[n][w][e]

[msg TUTORIAL_MSG05 [Classificação da Passagem de Bastão]]
[s]Você pode verificar a Classificação da Passagem de Bastão[n]de um membro do grupo na tela estatísticas.[n][w][e]

