[msg TUTORIAL_MSG01 [Cieli neri]]
[s]Com Medjed fora de cena, os Phantom Thieves[n] experimentam um novo boom de popularidade.[n] Tranquilizados por seus sucessos, eles decidem[n] procurar novos alvos de alto perfil.[n][w][e]

[msg TUTORIAL_MSG02 [Cieli neri]]
[s]Convencidos de que a morte de Wakaba foi[n] causada por uma parada mental, a equipe sai[n] na trilha do responsável, na esperança de[n] aumentar ainda mais sua popularidade.[n][w][e]

[msg TUTORIAL_MSG03 [Cieli neri]]
[s]Futaba sugere roubar dados do laptop de[n] Sae, já que ela também está investigando[n] prisões mentais, e um hesitante Makoto dá[n] sua aprovação.[n][w][e]

[msg TUTORIAL_MSG04 [Cieli neri]]
[s]Enquanto aguarda a análise dos dados, a equipe[n] vai para o Havaí para uma viagem escolar e[n] descobre que a fama dos Rogues agora é global.[n][w][e]

[msg TUTORIAL_MSG05 [Cieli neri]]
[s]Infelizmente, logo após retornarem para[n]casa, eles descobrem que o diretor de Shujin morreu[n]em circunstâncias suspeitas...[n][w][e]

