[msg TUTORIAL_MSG01 [Guarda]]
[s]Ao usar a [clr 2]Guarda[clr 27], você não apenas reduz o dano[n]que recebe, mas também fica temporariamente protegido[n]contra golpes e aflições.[n][w][e]

[msg TUTORIAL_MSG02 [Guarda]]
[s]Se você acredita que o inimigo realizará um ataque poderoso[n]ou terá como alvo suas fraquezas, a coisa mais sábia[n]a fazer é usar a Guarda para se proteger.[n][w][e]

[msg TUTORIAL_MSG03 [Guarda]]
[s]Depois de ativar a Guarda, você continuará a[n]proteger-se até o início do seu[n]próximo turno.[n][w][e]

