[msg TUTORIAL_MSG01 [Passeios com as gêmeas]]
[s]Agora você pode levar as gêmeas a várias instalações [n]que despertam o seu interesse. Quando estas saídas[n]estiverem disponíveis, a dupla pode ser encontrada esperando[n][f 4 2] logo após a Sala de Veludo.[n][w][e]

[msg TUTORIAL_MSG02 [Passeios com as gêmeas]]
[s]Para conduzi-las a esses lugares, você precisará verificar[n]as várias instalações espalhadas pela cidade.[n]Ao caminhar com as gêmeas,[n]o tempo vai passar.[n][w][e]

