[msg TUTORIAL_MSG01 [L'ultimo colpo]]
[s]Nos Mementos, a equipe finalmente encontra o Tesouro, o[n][clr 2]Santo Graal[clr 27]. No entanto, corrompido pela vontade das massas, ele se transformou em um deus do mal.[n][w][e]

[msg TUTORIAL_MSG02 [L'ultimo colpo]]
[s]Os Phantom Thieves são derrotados e o Graal[n] começa a fundir os Mementos com a realidade. Os[n] Rogues acordam a tempo de ver Shibuya[n] distorcida, quando começam a desaparecer impotentes.[n][w][e]

[msg TUTORIAL_MSG03 [L'ultimo colpo]]
[s]Acontece que o deus maligno assumiu a forma[n]de Igor e enganou [f 4 2] com seu[n]jogo, um daqueles em que ele nunca[n]poderia triunfar.[n][w][e]

[msg TUTORIAL_MSG04 [L'ultimo colpo]]
[s]O Meta-Nav e o Metaverse eram ferramentas[n]que o deus do mal havia usado para mostrar[n][f 4 2] a estupidez da raça humana.[n][w][e]

[msg TUTORIAL_MSG05 [L'ultimo colpo]]
[s][f 4 2]ele é salvo da morte certa quando[n]os gêmeos do Velvet Room se transformam[n]em Lavenza. O deus, agora convencido da vitória,[n]devolve o verdadeiro Igor e vai embora.[n][w][e]

[msg TUTORIAL_MSG06 [L'ultimo colpo]]
[s][f 4 2]fortalece a força de vontade dos[n]Ghost Thieves e a equipe se reúne na[n]Velvet Room para ouvir as justificativas de Igor.[n][w][e]

[msg TUTORIAL_MSG07 [L'ultimo colpo]]
[s]Antes de ser preso, Igor havia dado o que restava de seu poder a um mensageiro para encontrar um humano adequado para se tornar o Malandro.[n][w][e]

[msg TUTORIAL_MSG08 [L'ultimo colpo]]
[s]Morgana, agora não mais insegura de si mesma,[n] lidera os Phantom Thieves para enfrentar seu[n] último adversário.[n][w][e]

[msg TUTORIAL_MSG09 [L'ultimo colpo]]
[s]Assim começa a batalha final contra o deus[n]evil, com o destino do mundo pendurado por[n]a fio...[n][w][e]

