[msg D_TUTORIAL_26_mes01 [Navegando em Mementos]]
[s]Você pode viajar rapidamente dentro de Mementos.[n]Abra o mapa com [clr 2][f 1 10 53][clr 27], selecione [clr 2]Visão geral de Mementos[clr 27][n]e escolha para onde ir .[n][w][e]

[msg D_TUTORIAL_26_mes02 [Navegando em Mementos]]
[s]Isso só pode ser feito em [clr 2]certos locais[clr 27], como[n]a [clr 2]entrada de Mementos[clr 27] e em as [clr 2]plataformas de trem no[n]final de cada área [clr 27].[n][w][e]

