[msg TUTORIAL_MSG01 [Alterações]]
[s][clr 2]Alterações[clr 27] são estados negativos cujas as desvantagens[n] se aplicam por um tempo limitado.[n]As doenças são as seguintes:[n][w][e]

[msg TUTORIAL_MSG02 [Alterações]]
[s][clr 2]Queimado[clr 27]: Você recebe dano após agir.[n][clr 2]Congelado[clr 27]: Você não pode agir.[n][clr 2]Eletrocutado[clr 27]: Você não pode agir e corre o risco de eletrocutar[n]aqueles ao seu redor.[n][w][e]

[msg TUTORIAL_MSG03 [Alterações]]
[s][clr 2]Tonto[clr 27]: A precisão é bastante reduzida.[n][clr 2]Amnésia[clr 27]: Não é possível usar habilidades.[n][clr 2]Sono[clr 27]: Não é possível agir, mas o HP e SP irão recuperar[n]lentamente ao longo do tempo.[n][w][e]

[msg TUTORIAL_MSG04 [Alterações]]
[s][clr 2]Confusão[clr 27]: Tome ações que serão desvantajosas[n]para o grupo.[n][clr 2]Medo[clr 27]: Grande chance de ignorar ordens.[n]Existe o risco de fugir da batalha.[n][w][e]

[msg TUTORIAL_MSG05 [Alterações]]
[s][clr 2]Desespero[clr 27]: Você não pode agir e o SP diminui[n]com o tempo. A longo prazo, leva à morte.[n][clr 2]Fúria[clr 27]: Aumenta o ataque, mas diminui a defesa.[n]Além disso, você só pode usar ataques corpo a corpo.[n][w][e]

[msg TUTORIAL_MSG06 [Alterações]]
[s][clr 2]Subjugar[clr 27]: Você ataca aliados e da buff ou cura [n]para inimigos.[n][clr 2]Fome[clr 27]: O poder de todos ataques é[n]bastante reduzido.[n][w][e]

