[msg TUTORIAL_MSG01 [Il quinto colpo: Okumura]]
[s]Graças aos dados de Sae, Futaba descobre que o CEO[n]da Okumura Foods, [clr 2]Kunikazu Okumura[clr 27], está no[n]centro de várias investigações em andamento.[n][w][e]

[msg TUTORIAL_MSG02 [Il quinto colpo: Okumura]]
[s]Os Phantom Thieves então debatem se devem despertar o coração de[n] Okumura com base apenas na[n] opinião pública. A situação, porém, aumenta, forçando Morgana a fugir de casa.[n][w][e]

[msg TUTORIAL_MSG03 [Il quinto colpo: Okumura]]
[s][f 4 2]e os outros seguem Morgana até o Palácio de[n] Okumura, onde o encontram com uma mulher[n] chamada "Ladrão Esplêndido", mas não conseguem fazer as pazes.[n][w][e]

[msg TUTORIAL_MSG04 [Il quinto colpo: Okumura]]
[s]Investigando a identidade de Gorgeous Thief, a[n]equipe descobre que ela não é outra senão[n][clr 2]Haru Okumura[clr 27], filha de Kunikazu.[n][w][e]

[msg TUTORIAL_MSG05 [Il quinto colpo: Okumura]]
[s]Haru revela sua vontade de despertar o coração de seu pai[n]. Depois de se juntar aos Phantom Thieves, o grupo retorna ao Okumura Palace.[n][w][e]

[msg TUTORIAL_MSG06 [Il quinto colpo: Okumura]]
[s]Os Phantom Thieves conseguem derrotar a Sombra de Okumura[n] e roubar seu Tesouro. Então eles[n] se retiraram, esperando o despertar de seu coração.[n][w][e]

[msg TUTORIAL_MSG07 [Il quinto colpo: Okumura]]
[s]A equipe pega a entrevista coletiva de Okumura enquanto ele está festejando em Destinyland, mas a diversão dura pouco...[n][w][e]

[msg TUTORIAL_MSG08 [Il quinto colpo: Okumura]]
[s]Durante a conferência, Okumura sofre[n] uma parada mental repentina e morre logo depois.[n]Completamente sem relação com o que aconteceu, os Ladrões[n]Phantom estão surpresos.[n][w][e]

