[msg D_TUTORIAL_20_mes01 [Jose]]
[s]Ao falar com [clr 2]Jose[clr 27] em Mementos, você poderá trocar[n][clr 2]flores[clr 27] por itens. Dependendo do item que você está[n]procurando, a quantidade de flores necessárias mudará.[n]Quanto mais raro o item, mais flores serão necessárias.[n][w][e]

[msg D_TUTORIAL_20_mes02 [Jose]]
[s]Essas flores não podem existir fora de[n]Mementos, então tome cuidado.[n][clr 2]Você perderá as flores coletadas[clr 27] ao sair.[n][w][e]

