[msg TUTORIAL_MSG01 [Negociação com a Sombra]]
[s]Durante um Hold Up, você pode [clr 2]negociar[clr 27] com qualquer[n]sombra inimiga. Se for bem sucedido, você poderá[n]obter uma nova Persona.[n][w][e]

[msg TUTORIAL_MSG01_02 [Negociação com a Sombra]]
[s]Se o inimigo for uma Persona que você já possui, você[n]verá uma máscara ao lado do nome dele. Ao pedir[n]"[clr 2]Me dê seu poder[clr 27]", [clr 2]sua Persona ganhará XP[clr 27],[n]mesmo que não esteja equipada.[n][w][e]

[msg TUTORIAL_MSG02 [Negociação com a Sombra]]
[s]Decida se deseja derrotar seus inimigos rapidamente com[n]Ataque combina e ganhar experiência, ou negociar[n]com eles para obter uma Persona ou até[n]mesmo outra recompensa.[n][w][e]

