[msg TUTORIAL_MSG01 [Come combattere nelle Battaglie sfida]]
[s]Nas Batalhas de Desafio, você precisa se concentrar[n]em derrotar os inimigos[n]e causar dano ao mesmo tempo.[n][w][e]

[msg TUTORIAL_MSG02 [Come combattere nelle Battaglie sfida]]
[s]Para causar dano massivo, aumente o[n]poder de ataque do grupo e diminua a defesa dos inimigos.[n]Você pode derrubar o inimigo para usar ataques técnicos.[n][w][e]

[msg TUTORIAL_MSG03 [Come combattere nelle Battaglie sfida]]
[s]Você pode gravar um recorde obtendo pontos de bônus,[n]monitorando a ordem da batalha e avaliando[n]qual membro do grupo envolver no revezamento.[n][w][e]

