[msg TUTORIAL_MSG01 [Lançamento Final dos Companheiros]]
[s]Se você tiver uma pontuação baixa na [clr 2]rodada 4[clr 27], seu[n]companheiro de equipe pode pedir conselhos sobre como[n]eles devem terminar. Responder corretamente aumenta a[n]possibilidade de que eles irão realizar um lance final.[n][w][e]

[msg TUTORIAL_MSG02 [Lançamento Final dos Companheiros]]
[s]Quando seu companheiro de equipe termina dessa maneira,[n]sua sinergia com esse companheiro de equipe aumenta,[n]aumentando seu nível de [clr 2]Passe de bastão em 2[clr 27].[n][w][e]

