[msg D_TUTORIAL_35_mes01 [Itens de cura na sala segura]]
[s]Alguns itens, como [clr 2]Gotejamento de Cura[clr 27], só podem[n]ser usados nas Salas Seguras.[n][w][e]

[msg D_TUTORIAL_35_mes02 [Itens de cura na sala segura]]
[s]Você pode fazer uso desses itens entrando em uma[n]Sala Segura e selecionando "Consultar".[n][w][e]

[msg D_TUTORIAL_35_mes03 [Itens de cura na sala segura]]
[s]As áreas em que esses[n]objetos podem ser usados são limitadas. [n]No entanto, eles têm um poder de cura considerável[n], então use em caso de emergência.[n][w][e]

