[msg TUTORIAL_MSG01 [La risalita, parte 1]]
[s]Acompanhados por Akechi, os Phantom Thieves[n]infiltram-se no Palácio de Sae Niijima,[n]inspirado no estilo de um casino...[n][w][e]

[msg TUTORIAL_MSG02 [La risalita, parte 1]]
[s]Os Ladrões Fantasmas encontram e derrotam a Sombra de Sae.[n]Infelizmente, [f 4 2] ele é preso pela[n]polícia do mundo real, que entrou no Palácio...[n][w][e]

[msg TUTORIAL_MSG03 [La risalita, parte 1]]
[s][f 4 2]descobre que entre seus amigos[n]existe um [clr 2]traidor[clr 27]. Enquanto isso, a notícia de sua prisão circula por Tóquio...[n][w][e]

[msg TUTORIAL_MSG04 [La risalita, parte 1]]
[s][f 4 2]ele é levado para uma [clr 2]sala de interrogatório[clr 27][n]no subsolo e interrogado. Sae também o interroga,[n]ele finalmente fechando o círculo da história.[n][w][e]

[msg TUTORIAL_MSG05 [La risalita, parte 1]]
[s]Enquanto [f 4 2] luta contra os efeitos dos narcóticos e[n]não revela nada sobre os Phantom Thieves, um [clr 2]assassino[clr 27][n]enviado pelo verdadeiro culpado se aproxima...[n][w][e]

[msg TUTORIAL_MSG06 [La risalita, parte 1]]
[s]O assassino não é outro senão o próprio [clr 2]Goro Akechi[clr 27],[n]que aponta sua arma para [f 4 2] e o mata a[n]sangue frio. Notícia reporta rótulo[n]um suicídio...[n][w][e]

