[msg D_TUTORIAL_31_mes01 [Se escondendo]]
[s]Mova [clr 2][f 1 10 45][clr 27] para olhar[n]ao seu redor enquanto se esconde.[n][w][e]

[msg D_TUTORIAL_31_mes02 [Se escondendo]]
[s]Mover [clr 2][f 1 10 43][clr 27] permitirá que você altere[n]a direção que está olhando[n]ou indo para um local próximo.[n][w][e]

[msg D_TUTORIAL_31_mes03 [Se escondendo]]
[s]Você poderá emboscar o inimigo, mas também[n]realizar várias ações, como [clr 2]evitar inimigos[clr 27][n]e [clr 2]obter itens[clr 27] de baús.[n][w][e]

[msg D_TUTORIAL_31_mes04 [Se escondendo]]
[s]Se você tiver mais lugares para se mover,[n]você pode usar [f 1 10 78] para escolher seu destino.[n]Você também pode usar [f 1 10 76] para focar nos inimigos[n]e [f 1 10 77] para focar em baús.[n][w][e]

