[msg TUTORIAL_MSG01 [Indo para o Clube de Jazz]]
[s]Os amigos que você convidar para o Clube de Jazz[n]irão ganhar e melhorar diferentes[n]efeitos, que mudarão dependendo o dia.[n][w][e]

[msg TUTORIAL_MSG02 [Indo para o Clube de Jazz]]
[s]Se você visitar o Clube de Jazz em um dia em que [clr 2]um cantor[n]ao vivo se apresentar[clr 27], um coquetel especial será[n]servido. Além disso, os [clr 2]efeitos do coquetel serão[n]dobrados[clr 27] se for um dia da semana.[n][w][e]

