[msg TUTORIAL_MSG01 [Trocando Persona]]
[s]O potencial de [f 4 2] permite que ele possua[n] múltiplas Persona. Portanto, você pode [clr 2]trocar[clr 27][n][clr 2]livremente a Persona invocada[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Trocando Persona]]
[s]Quando você troca sua Persona, suas estatísticas,[n]afinidades elementais e as habilidades disponíveis,[n]mudarão em você para corresponder a Persona selecionada.[n][w][e]

[msg TUTORIAL_MSG03 [Trocando Persona]]
[s]No menu [clr 2]Persona[clr 27], você pode pressionar [clr 2][f 1 10 47] ou [f 1 10 48][clr 27] para[n]alterar sua Persona. Fora das batalhas,[n]pressione [f 1 10 25] e selecione uma [clr 2]Persona[clr 27] para trocar.[n][w][e]

[msg TUTORIAL_MSG04 [Trocando Persona]]
[s]Normalmente, você pode mudar de Persona quantas[n] vezes quiser, mas em batalha, você só pode fazer isso[n]apenas [clr 2]uma vez por turno[clr 27].[n][w][e]

