[msg TUTORIAL_MSG01 [Passar um tempo no Leblanc]]
[s]À noite, você poderá realizar várias atividades que[n]o ajudarão na vida cotidiana.[n][w][e]

[msg TUTORIAL_MSG02 [Passar um tempo no Leblanc]]
[s]Estude na [clr 2]mesa[clr 27] para melhorar seu [f 4 11 0][clr 26][f 4 12 0][clr 27].[n]No balcão você pode [clr 2]leia [clr 27] e aprenda coisas diferentes. Usando[n]as ferramentas de limpeza no banheiro para [clr 2]limpar[clr 27] o Leblanc[n]irá melhorar seu [f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Passar um tempo no Leblanc]]
[s]Se você encontrar uma [clr 2]palavras cruzadas[clr 27] na mesa[n]no fundo, tente resolvê-lo. Se você for bem-sucedido,[n]seu [f 4 11 0][clr 26][f 4 12 0][clr 27] melhorará[n]sem perder tempo.[n][w][e]

