[msg TUTORIAL_MSG01 [Massagem especial da Kawakami]]
[s]Agora, à noite, você pode usar o telefone do Leblanc[n]para pedir a Kawakami para acompanhá-lo[n]e fazer uma [clr 1]massagem especial[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Massagem especial da Kawakami]]
[s]A [clr 1]Massagem Especial[clr 27] da Kawakami removerá a exaustão[n]e permitirá que você saia à noite, mesmo depois[n]de se aventurar em um Palácio ou Lembranças.[n][w][e]

