[msg TUTORIAL_MSG01 [Formando um contrato com os confidentes]]
[s]Às vezes, uma pessoa que você conhece na cidade pode[n]tornar-se seu confidente. Se seus objetivos estiverem [n]alinhados, você poderá firmar um[n]contrato com eles.[n][w][e]

[msg TUTORIAL_MSG02 [Formando um contrato com os confidentes]]
[s]Conforme seu relacionamento se aprofunda, sua classificação com[n]aquele Confidente aumentará. Isso permitirá que[n]você crie Personas ainda mais fortes.[n][w][e]

[msg TUTORIAL_MSG03 [Formando um contrato com os confidentes]]
[s]Faça o possível para encontrar confidentes e fortalecer[n]esses relacionamentos.[n][w][e]

