[msg TUTORIAL_MSG01 [Riprendersi la realtà]]
[s]Há [clr 2]Maruki[clr 27] esperando por eles. Foi ele quem criou a falsa realidade por meio da ciência psi-cognitiva. Para[n]ajudar as pessoas a escapar da infelicidade, ele criou um[n]mundo onde os desejos de todos poderiam se tornar realidade.[n][w][e]

[msg TUTORIAL_MSG02 [Riprendersi la realtà]]
[s]Kasumi também estava sob sua influência. O que[n]acreditava ser [clr 2]Kasumi era na verdade Sumire[clr 27]. Porque[n] Kasumi morreu por causa dela, Sumire desejou[n] "ser Kasumi" para realizar seus sonhos.[n][w][e]

[msg TUTORIAL_MSG03 [Riprendersi la realtà]]
[s]Mas Sumire não é a única vítima, os[n]Phantom Thieves também foram enganados. Assim que[n] a verdade é descoberta, [f 4 2] e Akechi retornam ao Palácio[n] para destruir o mundo ideal criado por Maruki.[n][w][e]

[msg TUTORIAL_MSG04 [Riprendersi la realtà]]
[s]No entanto, Sumire, que "deseja ser Kasumi", não quer desistir da realidade de Maruki. Mas com a ajuda de [clr 2]os outros[n]membros do Phantom Thieves[clr 27], [f 4 2] e Akechi[n]derrota a Persona Fora de Controle de Sumire.[n][w][e]

[msg TUTORIAL_MSG05 [Riprendersi la realtà]]
[s]Lavenza informa [f 4 2] que Maruki possui uma [clr 2]Pessoa[n]com o poder de realização[clr 27]. Graças a esse[n]poder e aos Mementos, ele consegue distorcer a realidade.[n][w][e]

[msg TUTORIAL_MSG06 [Riprendersi la realtà]]
[s]Isso só acontece porque os Phantom Thieves, que[n] personificavam as esperanças do povo, ansiavam por[n] esta realidade. Ao saber disso, os Phantom Thieves[n] ficam chocados.[n][w][e]

[msg TUTORIAL_MSG07 [Riprendersi la realtà]]
[s]Embora eles já tenham evitado a fusão[n] entre a realidade e o Memento no passado, o poder de Maruki é o pontapé inicial novamente. A um mês do prazo,[n]i Thieves decide despertar seu coração.[n][w][e]

[msg TUTORIAL_MSG08 [Riprendersi la realtà]]
[s]Entrando no Palácio, eles encontram [clr 2]Sumire[clr 27], que[n]decidiu ser ela mesma e ajudar os[n]Phantom Thieves a lutar contra Maruki.[n]Juntos, eles avançam em direção ao Tesouro.[n][w][e]

[msg TUTORIAL_MSG09 [Riprendersi la realtà]]
[s]Na noite de 2 de fevereiro, [f 4 2] encontra o caminho,[n]rejeita a realidade criada por Maruki e entrega a carta[n]de desafio a ele. Como terminará esta batalha final, o[n]desafio pelos próprios ideais?[n][w][e]

