[msg TUTORIAL_MSG01 [Prevenire la fuga del nemico]]
[s]Quando um inimigo em pânico tenta fugir,[n] você pode pedir a ajuda da Guilda dos Ladrões[n] para impedi-los de escapar.[n][w][e]

[msg TUTORIAL_MSG02 [Prevenire la fuga del nemico]]
[s]No entanto, você só pode pedir ajuda um número[n]limitado de vezes durante uma infiltração[n]no Metaverso. As solicitações serão redefinidas[n] a cada alteração de data.[n][w][e]

