[msg TUTORIAL_MSG01 [Prazo para se infiltrar no Palácio]]
[s]Se você não conseguir concluir o plano[n]antes do prazo, isso acionará o [clr 2]Fim do Jogo[clr 27].[n]Sempre preste atenção ao tempo restante.[n][w][e]

[msg TUTORIAL_MSG02 [Prazo para se infiltrar no Palácio]]
[s]Os palácios contêm muitos inimigos poderosos. Consulte[n]seus aliados e aproveite as diferentes [clr 2]estruturas presentes[n]na cidade[clr 27] para garantir uma infiltração bem-sucedida.[n][w][e]

