[msg TUTORIAL_MSG01 [Infiltrando nas Lembranças]]
[s]À medida que os rumores sobre os Phantom Thieves[n] se espalham, os pedidos aparecerão no site[n]Phantom Aficionado. Use estas[n]dicas para rastrear alvos em Mementos.[n][w][e]

[msg TUTORIAL_MSG02 [Infiltrando nas Lembranças]]
[s][clr 2]Explorar Mementos e derrotar Sombras[clr 27][n]são uma maneira eficaz de [clr 2]ganhar experiência[clr 27].[n]Torne-se mais forte lutando contra Sombras comuns e raras[n]em Mementos.[n][w][e]

