[msg TUTORIAL_MSG01 [Coquetéis no Clube de Jazz]]
[s]Os coquetéis servidos no clube de jazz proporcionam[n]benefícios às Personas dos membros do grupo.[n]A carta de bebidas varia diariamente:[n][w][e]

[msg TUTORIAL_MSG02 [Coquetéis no Clube de Jazz]]
[s]Segunda-feira: "Mightini" — Subir de nível e máximo [clr 2]HP[clr 27] +20[n]Terça-feira: "Power Fizz" — Aumento de estatísticas ([clr 2]St[clr 27], [clr 2]En[clr 27], [clr 2]Lu[clr 27])[n][w][e]

[msg TUTORIAL_MSG03 [Coquetéis no Clube de Jazz]]
[s]Quarta-feira: "Soultini" — Subir de nível e máximo [clr 2]SP[clr 27] +20[n]Quinta-feira: "Magic Fizz" — Aumento de estatísticas ([clr 2]Ma[clr 27], [clr 2]Ag[clr 27], [clr 2]Lu[clr 27])[n][w][e]

[msg TUTORIAL_MSG04 [Coquetéis no Clube de Jazz]]
[s]Sexta-feira: "Omni-Fizz" — Max [clr 2]HP[clr 27] +10, max [clr 2]SP[clr 27] +5,[n]e aumento de estatísticas ([clr 2]St[clr 27], [clr 2]Ma[clr 27], [clr 2]En[clr 27], [clr 2]Ag[clr 27], [clr 2]Lu[clr 27])[n][w] [e]

[msg TUTORIAL_MSG05 [Coquetéis no Clube de Jazz]]
[s]Sábado: Menu rotativo de coquetéis de segunda a sexta[n]Domingo: Fornece uma [clr 2]nova habilidade[clr 2] - muda semanalmente[n][w][e]

