[msg TUTORIAL_MSG01 [Pontuações altas em Desafio de Batalhas]]
[s]As pontuações dos Desafios de batalhas são baseadas em [clr 2]danos[n]infligidos[clr 27]. Causar dano massivo ajudará[n]a alcançar um recorde.[n][w][e]

[msg TUTORIAL_MSG02 [Pontuações altas em Desafio de Batalhas]]
[s]Use [clr 2]Habilidades de suporte[clr 27], [clr 2]Passe de bastão[clr 27][n]e [clr 2]Ataque Técnico[clr 27] para obter uma pontuação alta.[n]Efeitos de bônus darão a você uma pontuação ainda maior.[n][w][e]

[msg TUTORIAL_MSG03 [Dummy]]
[s]Fictício[n][w][e]

[msg TUTORIAL_MSG04 [Dummy]]
[s]Fictício[n][w][e]

