[msg TUTORIAL_MSG01 [Comandos para pesca (parte 2)]]
[s]Pressione [clr 2][f 1 10 22][clr 27] quando um peixe morder para fisgar o peixe antes[n]ele escapar.[n][w][e]

[msg TUTORIAL_MSG02 [Comandos para pesca (parte 2)]]
[s]Mova o ícone da boinha com [f 1 10 43] para a zona vermelha[n]e pressione rapidamente [clr 2][f 1 10 22][clr 27] para enrolá-la. o ícone está fora[n]da zona vermelha.[n][w][e]

[msg TUTORIAL_MSG03 [Comandos para pesca (parte 2)]]
[s]A vara de pescar tem força limitada. Se[n]a boia atingir as bordas do indicador[n]muitas vezes, a linha se romperá e o peixe irá escapar.[n][w][e]

