[msg TUTORIAL_MSG01 [Personalização de armas]]
[s][clr 2]A Personalizão[clr 27] de armas foi adicionado ao menu da loja de Iwai[n], o Intocável. Agora as [clr 2]armas de longo alcance[clr 27], como[n]pistolas, podem ser personalizadas.[n][w][e]

[msg TUTORIAL_MSG02 [Personalização de armas]]
[s]Você pode instalar uma peça personalizada por arma.[n]Quanto mais alto o Rank do seu Confidente, mais[n]partes personalizáveis você poderá escolher.[n][w][e]

