[msg D_TUTORIAL_08_mes01 [Atacando inimigos]]
[s]A batalha começa quando você ataca um inimigo próximo[n] pressionando [clr 2][f 1 10 22][clr 27]. Fique de olho no [clr 2]ícone[n]vermelho[clr 27] que aparecerá quando você estiver ao alcance.[n][w][e]

[msg D_TUTORIAL_08_mes02 [Atacando inimigos]]
[s]Se você se aproximar de um inimigo por trás sem ser detectado,[n]o [clr 2]ícone de emboscada[clr 27] aparecerá. Ataque imediatamente e você[n]terá uma vantagem na batalha.[n][w][e]

