[msg TUTORIAL_MSG01 [Regali di Natale]]
[s]Graças ao seu Presente de Natal,[n]o vínculo com o Confidente crescerá[n]mais rápido quando você estiver de posse de[n]uma Persona de seu próprio Arcano.[n][w][e]

[msg TUTORIAL_MSG02 [Regali di Natale]]
[s]Se você quiser sair várias vezes com um Confidant[n] sem aumentar seu Rank, tente não trazer[n] uma Persona de seu próprio Arcanum com você.[n][w][e]

