[msg TUTORIAL_MSG01 [Trabalho de meio período]]
[s]Trabalhos de meio período farão com que o tempo passe, mas[n]também permitem que você ganhe dinheiro e aumente estatísticas[n]como [f 4 11 1][clr 26][f 4 12 1][clr 27] e [f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Trabalho de meio período]]
[s]Alguns empregos exigem que você tenha [clr 2]estatísticas altas[n]o suficiente[clr 27] antes de se candidatar.[n]Dependendo do trabalho, você só pode trabalhar durante [n]certas [clr 2]horas do dia[clr 27].[n][w][e]

