[msg TUTORIAL_MSG01 [Convites dos Confidentes]]
[s]Os confidentes irão convidá-lo para passar um tempo[n]com eles via MI. Algumas mensagens serão mais[n]importantes do que outras.[n][w][e]

[msg TUTORIAL_MSG02 [Convites dos Confidentes]]
[s]Você pode aceitar o convite respondendo à mensagem,[n]mas não será forçado a responder[n]imediatamente.[n][w][e]

[msg TUTORIAL_MSG03 [Convites dos Confidentes]]
[s]As mensagens de texto não respondidas serão[n]marcadas como [clr 2]Aguardando[clr 27].[n][w][e]

[msg TUTORIAL_MSG04 [Convites dos Confidentes]]
[s]Se você esperar muito para responder, o convite[n] irá expirar. Nem todos os MIs precisam de uma[n]resposta. Só aceite convites de[n] pessoas em quem você está interessado.[n][w][e]

