[msg TUTORIAL_MSG01 [Indo para a loja de segunda mão]]
[s]Na loja de segunda mão, você pode vender [clr 2]armadura suja[clr 27][n]sua. Dependendo do que a armadura suja[n]era originalmente, ela pode alcançar um preço decente.[n][w][e]

[msg TUTORIAL_MSG02 [Indo para a loja de segunda mão]]
[s]Para cada item de roupa que você vender, você obterá[n][clr 2]pontos de loja[clr 27], que podem ser trocados por [clr 2]prêmios[clr 27][n]na loja. Veja se você pode encontrar algo útil![n][w][e]

