[msg D_TUTORIAL_27_mes01 [Recursos de Ladrão]]
[s]Pressione [clr 2][f 1 10 35][clr 27] enquanto investiga o Metaverso para usar[n]os recursos de ladrão, dando a você acesso a vários recursos[n]úteis que ajudarão no seu progresso.[n][w][e]

[msg D_TUTORIAL_27_mes02 [Recursos de Ladrão]]
[s]A autocura usa as habilidades de cura de[n]companheiros de equipe em [clr 2]todo o grupo[clr 27]. No entanto, lembre-se[n]que [clr 2]o SP solicitado ainda será consumido[clr 27].[n][w][e]

[msg D_TUTORIAL_27_mes03 [Recursos de Ladrão]]
[s]Você pode usar [clr 2]ferramentas de infiltração[clr 27], como[n][clr 2]Parede de fumaça[clr 27] para fugir rapidamente da luta.[n]Essas ferramentas lhe darão uma vantagem na batalha![n][w][e]

