[msg TUTORIAL_MSG01 [Mercadorias obscuras]]
[s]Por meio do Negócio obscuro, você pode obter itens raros[n] e incomuns. As compras serão entregues a[n]você após alguns dias. Você pode solicitar[n]apenas um pacote por vez.[n][w][e]

[msg TUTORIAL_MSG02 [Mercadorias obscuras]]
[s]Quanto mais itens você comprar na Negócio obscuro,[n]mais produtos estarão disponíveis para venda.[n]Invista dinheiro e descubra quais novos[n]itens valiosos estarão disponíveis no futuro.[n][w][e]

