[msg D_TUTORIAL_04_mes01 [Mau tempo]]
[s]Em dias de [clr 2]mau tempo[clr 27] como[n]dias de chuva, em Mementos irá ser mais perigoso.[n]No entanto, você terá [clr 2]chance de obter itens extras[clr 27].[n][w][e]

[msg D_TUTORIAL_04_mes02 [Mau tempo]]
[s]Você encontrará muito mais inimigos, mas às vezes[n]pode haver [clr 2]inimigos raros[clr 27].[n][w][e]

[msg D_TUTORIAL_04_mes03 [Mau tempo]]
[s]Além disso, você pode encontrar itens de maior[n]valor e haverá [clr 2]mais baús[clr 27].[n]Aproveite ao máximo essas oportunidades.[n][w][e]

