[msg TUTORIAL_MSG01 [Regole di Magnate]]
[s]La forza di una carta è determinata dal numero.[n]Ogni carta deve battere la precedente e il numero di carte[n]in gioco dev'essere rispettato (come le coppie). La carta [clr 2][n]più debole è il 3[clr 27], ma la [clr 2]più forte è il 2[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Regole di Magnate]]
[s]O jogador com [clr 2]3 de ouros[clr 27] começa e[n]o mendigo começa o próximo jogo. Para mais[n]informações, vá para "Tutorial" ou pressione[n][f 1 10 51] durante o jogo.[n][w][e]

