[msg TUTORIAL_MSG01 [Trabalhando na Beef Bowl Shop]]
[s]Trabalhar na Beef Bowl Shop vai fazer com que o tempo passe,[n]mas além de ganhar dinheiro, seu[n][f 4 11 2][clr 26][f 4 12 2][clr 27] vai melhorar.[n][w][e]

[msg TUTORIAL_MSG02 [Trabalhando na Beef Bowl Shop]]
[s]Alguns dias a loja estará mais movimentada do que o normal[n]e você terá que se lembrar de muitos pedidos.[n]Tente manter a calma. Se você conseguir se safar,[n]poderá ganhar mais dinheiro do que o normal.[n][w][e]

