[msg D_TUTORIAL_28_mes01 [Usando o gancho]]
[s]Você pode usar o gancho para acessar[n]locais específicos em um palácio, aonde[n]você encontrará caminhos ou baús ocultos.[n][w][e]

[msg D_TUTORIAL_28_mes02 [Usando o gancho]]
[s]Quando você estiver perto de um local onde possa[n]ganchar, [clr 2]sua mão esquerda irá bilhar em [n]azul[clr 27], ela começará a [clr 2]piscar[clr 27][n]quando você puder usá-lo.[n][w][e]

[msg D_TUTORIAL_28_mes03 [Usando o gancho]]
[s]Usando o [clr 1]Terceiro Olho[clr 27] irá ajuda-lo a localizar[n]alvos de gancho adequados. Certifique-se de verificar[n]várias posições para fazer melhor uso do gancho![n][w][e]

