[msg TUTORIAL_MSG01 [Pedidos Especiais]]
[s]Em certas batalhas, você poderá emitir um pedidos especial.[n]Se essas estratégias forem bem-sucedidas,[n][clr 2]o resultado da batalha mudará radicalmente a seu favor.[clr 27][n][w][e]

[msg TUTORIAL_MSG02 [Pedidos Especiais]]
[s]Certifique-se de escolher o membro do grupo que[n]você acha que tem a melhor chance de sucesso.[n][w][e]

[msg TUTORIAL_MSG03 [Pedidos Especiais]]
[s]No entanto, lembre-se de que esse membro do[n]grupo agirá por conta própria, forçando você a[n]lutar com [clr 2]um companheiro de equipe a menos[clr 27] por um[n]período de tempo.[n][w][e]

