[msg TUTORIAL_MSG01 [Il terzo colpo: Kaneshiro]]
[s]Em uma viagem escolar, [f 4 2] e os outros[n] conhecem um jovem detetive chamado [clr 2]Goro[n]Akechi[clr 27], que está convencido de que os Phantom Thieves[n]estão obstruindo a justiça.[n][w][e]

[msg TUTORIAL_MSG02 [Il terzo colpo: Kaneshiro]]
[s]Mais tarde, a presidente do conselho estudantil,[n][clr 2]Makoto Niijima[clr 27], confronta os Phantom Thieves[n]e exige que eles encontrem um chefe da máfia,[n]caso contrário ela irá expor seu segredo.[n][w][e]

[msg TUTORIAL_MSG03 [Il terzo colpo: Kaneshiro]]
[s]Os Phantom Thieves descobrem o nome do chefe da[n]máfia, [clr 2]Junya Kaneshiro[clr 27], mas não conseguem[n]encontrá-lo. Portanto, eles não podem se infiltrar no palácio dela.[n][w][e]

[msg TUTORIAL_MSG04 [Il terzo colpo: Kaneshiro]]
[s]Makoto usa a si mesma como isca para saber o paradeiro de[n]Kaneshiro, mas leva os Ladrões[n]para uma armadilha. Como resultado, eles são forçados[n]o a pagar uma quantia substancial a Kaneshiro.[n][w][e]

[msg TUTORIAL_MSG05 [Il terzo colpo: Kaneshiro]]
[s]Cheio de culpa, Makoto ajuda [f 4 2] e os[n] outros a obter acesso ao Palácio de Kaneshiro.[n] Dentro dele, sua Persona desperta e os ajuda a[n] derrotar a Sombra de Kaneshiro.[n][w][e]

[msg TUTORIAL_MSG06 [Il terzo colpo: Kaneshiro]]
[s]A Sombra de Kaneshiro revela que outra pessoa[n] está se infiltrando nos Palácios. Alguém que[n]pode estar relacionado a [clr 2]paradas mentais[clr 27] e[n][clr 2]raptus[clr 27].[n][w][e]

[msg TUTORIAL_MSG07 [Il terzo colpo: Kaneshiro]]
[s]Seja o "cara da[n]máscara negra" mencionado pela Sombra de Madarame...?[n][w][e]

