[msg TUTORIAL_MSG01 [Cartas de habilidade]]
[s]Uma carta de habilidade é um tipo de item especial[n]com o qual você pode ensinar uma de suas Personas[n]uma habilidade específica.[n][w][e]

[msg TUTORIAL_MSG02 [Cartas de habilidade]]
[s]Estas cartas de habilidades só podem ser usadas nas Personas[n][f 4 2]que possui atualmente em seu estoque.[n]O cartão será consumido após o uso, então use [n]eles com sabedoria.[n][w][e]

