[msg TUTORIAL_MSG01 [Informazioni da Mishima]]
[s]Mishima fornecerá informações sobre[n]objetivos via MI logo após a escola.[n][w][e]

[msg TUTORIAL_MSG02 [Informazioni da Mishima]]
[s]As informações vão desde as identidades dos[n]alvos até fofocas obscuras sobre eles.[n][w][e]

[msg TUTORIAL_MSG03 [Informazioni da Mishima]]
[s]As informações que você obtém de Mishima serão[n]registradas em [clr 2]Solicitações[clr 27] no[n]menu principal. Verifique-os pressionando [f 1 10 25].[n][w][e]

