[msg TUTORIAL_MSG01 [Usare le gabbie di battuta]]
[s]O uso de gaiolas de rebatidas vai[n]passar o tempo, mas você receberá recompensas[n]com base no seu desempenho.[n]seu [f 4 11 2][clr 26][f 4 12 2][clr 27] também melhorará.[n][w][e]

[msg TUTORIAL_MSG02 [Usare le gabbie di battuta]]
[s]Você terá um total de 5 lançamentos. Acertar todos os cinco[n] arremessos lhe renderá o [clr 2]prêmio de rebatedor[clr 27], enquanto acertar[n]um home run lhe renderá o [clr 2]prêmio de home run[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Usare le gabbie di battuta]]
[s]As atividades disponíveis variam de acordo com a hora do dia.[n]À noite, você não ganhará nenhum prêmio, mas poderá [clr 2]jogar quantas[n]piadas quiser[clr 27]. Por atingir [clr 2]3[clr 27] home runs, você ganhará[n]um ingresso para uma [clr 2]sessão diurna gratuita[clr 27].[n][w][e]

