[msg D_TUTORIAL_29_mes01 [Comandi di battaglia del dungeon]]
[s]Pressionar [clr 2][f 1 10 44][clr 27] enquanto explora uma[n]masmorra fará com que você pare e abra[n]i [clr 2]comandos de batalha[clr 27].[n][w][e]

[msg D_TUTORIAL_29_mes02 [Comandi di battaglia del dungeon]]
[s]Enquanto os Comandos de Batalha estiverem abertos,[n]os inimigos não se moverão, então você pode usar[n]as [clr 2]ferramentas de infiltração[clr 27] para surpreendê-los.[n][w][e]

[msg D_TUTORIAL_29_mes03 [Comandi di battaglia del dungeon]]
[s]Você também pode usar a [clr 2]autocura[clr 27][n]para curar instantaneamente sua equipe.[n]Lembre-se disso ao explorar.[n][w][e]

