[msg D_TUTORIAL_17_mes01 [Demônio do Tesouro]]
[s]Objetos quebráveis podem conter [clr 2]Treasure Demons[clr 27],[n]especialmente quando o [clr 2]nível de segurança é alto[clr 27].[n]Eles também podem aparecer em encontros normais. Ao derrotá-los[n]você ganhará muitos pontos de experiência.[n][w][e]

[msg D_TUTORIAL_17_mes02 [Tesouro do Demônio]]
[s]Se você convencer alguém a se tornar uma de suas[n]Personas, poderá usá-lo como material de fusão.[n]No entanto, um Demônio do Tesouro [clr 2]não pode ser usado[n]em batalha[clr 27]. [n][w][e]

