[msg D_TUTORIAL_32_mes01 [Desvios em Mementos]]
[s]Ao explorar os Mementos, você pode acabar em[n]uma área que parece [clr 2]diferente do normal[clr 27].[n][w][e]

[msg D_TUTORIAL_32_mes02 [Desvios em Mementos]]
[s]Significa que há um [clr 2]desvio[clr 27] naquela área.[n]Em um plano desviado pode haver efeitos que[n]ajudam ou atrapalham a exploração.[n][w][e]

[msg D_TUTORIAL_32_mes03 [Desvios em Mementos]]
[s]Na maioria dos casos, [clr 2]eventos bons e ruins ocorrerão[n]simultaneamente[clr 27]. Quando você sai de um andar desviado,[n]os efeitos desaparecem. Certifique-se de saber[n]quais são as diferenças antes de avançar. [n][w][e]

