[msg TUTORIAL_MSG01 [Enviando o carta de desafio]]
[s]Preste atenção aos seguintes pontos quando[n]você precisar enviar uma carta de desafio.[n][w][e]

[msg TUTORIAL_MSG02 [Enviando o carta de desafio]]
[s]Conclua todos os preparativos [clr 2]antes de enviar[n]a carta de desafio[clr 27]. Depois de tomar esta[n]decisão, você [clr 2]irá para casa[clr 27] e [clr 2]começará o[n]dia seguinte diretamente no Palácio[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Enviando o carta de desafio]]
[s]Depois de enviar a carta de desafio[n]e obter o Tesouro, você [clr 2]não pode[n]voltar ao Palácio correspondente[clr 27]. Antes de fazer isso,[n] então, certifique-se de abrir todos os baús.[n][w][e]

[msg TUTORIAL_MSG04 [Enviando o carta de desafio]]
[s]É possível entrar no Palácio em busca de[n]itens ou Persona sem enviar a carta.[n]No entanto, fique de olho no tempo restante.[n][w][e]

