[msg TUTORIAL_MSG01 [Melhore as habilidades sociais]]
[s]Certas situações exigem os seguintes talentos:[n][f 4 11 0][clr 26][f 4 12 0][clr 27], [f 4 11 1][clr 26][f 4 12 1][clr 27], [f 4 11 2][clr 26][f 4 12 2][clr 27],[n][f 4 11 3][clr 26][f 4 12 3][clr 27] e [f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Melhore as habilidades sociais]]
[s]Você pode treinar essas habilidades por meio de várias atividades[n]na cidade, como a leitura de livros. Olhe ao redor e[n] veja o que você pode encontrar.[n][w][e]

