[msg D_TUTORIAL_09_mes01 [Viagem rápida]]
[s]Agora você pode usar a [clr 2]viagem rápida[clr 27]. Abra[n]o mapa com [clr 2][f 1 10 53][clr 27] e selecione uma sala segura já visitada[n]para ir para lá instantaneamente.[n][w][e]

[msg D_TUTORIAL_09_mes02 [Viagem rápida]]
[s]Você também pode retornar rapidamente de uma[n]Sala Segura para a entrada do palácio.[n]Você pode usar a Viagem rápida[n][clr 2]somente nesses dois locais[clr 27].[n][w][e]

