[msg TUTORIAL_MSG01 [Duplicação]]
[s]Agora você pode pedir a Yusuke para usar sua habilidade de[n][clr 1]Duplicação[clr 27] para criar cópias de Cartas de Habilidade.[n][w][e]

[msg TUTORIAL_MSG02 [Duplicação]]
[s]Para copiar um carta de habilidade, dê a Yusuke[n]uma carta em braco e a carta que deseja copiar.[n]Ambos podem ser coletadas no [clr 2]próximo dia[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Duplicação]]
[s][clr 2]O Cartão Branco será transformado[clr 27] para criar[n]o novo Cartão de Habilidade. Yusuke devolverá as cartas[n]novas e originais para você.[n][w][e]

[msg TUTORIAL_MSG04 [Duplicação]]
[s]Cartões brancos podem ser obtidos[n][clr 2]procurando itens em Momentos[clr 27].[n]Tente encontrar o máximo possível.[n][w][e]

