[msg TUTORIAL_MSG01 [habilidades herdadas]]
[s]Quando você mesclar uma nova Persona,[n]ela poderá herdar algumas habilidades[n]que pertenciam à Persona original.[n][w][e]

[msg TUTORIAL_MSG02 [habilidades herdadas]]
[s]As habilidades que podem ser herdadas dependem[n]do tipo de Persona que estão sendo fundidas.[n][clr 2]Quanto mais habilidades as Personas originais tiverem,[n]mais habilidades podem ser herdadas[clr 27].[n][w][e]

