[msg TUTORIAL_MSG01 [O que fazer entre as missões]]
[s]Há uma variedade de atividades para fazer na cidade[n] antes de definir seu próximo objetivo.[n][w][e]

[msg TUTORIAL_MSG02 [O que fazer entre as missões]]
[s]Visite lugares diferentes e ouça fofocas.[n]Você pode encontrar alguém que tenha[n]novas informações para você.[n][w][e]

[msg TUTORIAL_MSG03 [O que fazer entre as missões]]
[s]Fortalecer o vínculo com seus Confidentes pode[n]conceder várias vantagens aos Phantom Thieves.[n]Use seu tempo com sabedoria para obter[n]os melhores resultados.[n][w][e]

