[msg TUTORIAL_MSG01 [Un mondo in pericolo]]
[s]Masayoshi Shido finalmente tem um despertar de[n]coração e confessa seus crimes ao vivo[n]nacional. Os Phantom Thieves estão convencidos de que a sociedade vai se recuperar.[n][w][e]

[msg TUTORIAL_MSG02 [Un mondo in pericolo]]
[s]Os Phantom Thieves se deleitam com seu sucesso,[n]convencidos de que a popularidade de Shido vai despencar[n]à luz de sua confissão.[n][w][e]

[msg TUTORIAL_MSG03 [Un mondo in pericolo]]
[s]Mas as coisas tomam um rumo inesperado.[n]O público se recusa a aceitar[n]os crimes de Masayoshi Shido e de repente esquece[n]a existência dos Phantom Thieves.[n][w][e]

[msg TUTORIAL_MSG04 [Un mondo in pericolo]]
[s]Desesperados, os Phantom Thieves e Sae ponderam sobre o próximo movimento. Como Shido fez uso[n]do Metaverso, construir um caso contra seus[n]crimes seria quase impossível.[n][w][e]

[msg TUTORIAL_MSG05 [Un mondo in pericolo]]
[s]Com a opinião pública paralisada, os Phantom Thieves[n]devem encontrar uma solução rapidamente, mas não podem[n]acordar corações um por um.[n][w][e]

[msg TUTORIAL_MSG06 [Un mondo in pericolo]]
[s]Morgana então lembra que nos [clr 2]Mementos, ou seja,[n]o Palácio de todos, há um Tesouro[clr 27] que,[n]se roubado, poderia trazer as massas de volta à razão.[n][w][e]

[msg TUTORIAL_MSG07 [Un mondo in pericolo]]
[s]Mas isso causaria o desaparecimento do próprio[n]Metaverse, decretando o fim dos Phantom Thieves.[n][w][e]

[msg TUTORIAL_MSG08 [Un mondo in pericolo]]
[s]Desanimada por ela não poder mais despertar[n]corações, mas inabalável em suas crenças,[n]a equipe viaja para os Mementos para um último assalto...[n][w][e]

