[msg TUTORIAL_MSG01 [Relaxando na aula da Kawakami]]
[s]Com a ajuda da Kawakami, você poderá relaxar nas aulas[n]em determinados dias. Use esse tempo[n]livre para fazer várias coisas, como[n][clr 2]ler[clr 27] ou criar[n][clr 2]ferramentas de infiltração[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Relaxando na aula da Kawakami]]
[s]No entanto, se você optar por estudar,[n]você ganhará [f 4 11 0][clr 26][f 4 12 0][clr 27].[n]Lembre-se disso.[n][w][e]

