[msg TUTORIAL_MSG01 [Fraquezas e Mais 1]]
[s]Cada habilidade tem um [clr 2]elemento[clr 27] diferente e cada inimigo[n]é [clr 2]fraco[clr 27] para apenas alguns deles.[n]Ao atacar a fraqueza de um inimigo, você causará mais dano[n]e o derrubará.[n][w][e]

[msg TUTORIAL_MSG02 [Fraquezas e Mais 1]]
[s]Depois de derrubar um inimigo, você ganha uma[n]ação adicional. Esta mecânica chama-se [clr 2]Mais 1[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Fraquezas e Mais 1]]
[s]Se você derrubar outro inimigo logo depois, obtenha[n]mais 1 adicional e assim por diante, desde que[n]você ataque as fraquezas do inimigo.[n][w][e]

