[msg TUTORIAL_MSG01 [Il primo colpo: Kamoshida]]
[s]Em Shujin, há rumores de um suposto caso[n]entre o treinador de vôlei, [clr 2]Suguru Kamoshida[clr 27],[n]e uma estudante, [clr 2]Ann Takamaki[clr 27]. No entanto, sua[n]glória passada leva os professores ao silêncio.[n][w][e]

[msg TUTORIAL_MSG02 [Il primo colpo: Kamoshida]]
[s]Depois de se encontrarem em um estranho castelo, Ryuji[n]e [f 4 2] são ameaçados por um rei que se parece[n]misteriosamente com Kamoshida. Mais tarde, eles descobrem[n]que é sua [clr 2]Sombra[clr 27], seu verdadeiro eu.[n][w][e]

[msg TUTORIAL_MSG03 [Il primo colpo: Kamoshida]]
[s]Em seu [clr 2]Palácio[clr 27], onde os pensamentos[n]mais sombrios de sua mente distorcida se manifestam, as suspeitas de[n]Ryuji sobre o abuso e assédio sexual de[n]Kamoshida são confirmadas.[n][w][e]

[msg TUTORIAL_MSG04 [Il primo colpo: Kamoshida]]
[s]Outrora uma estrela da equipe de atletismo, Ryuji[n] já experimentou a crueldade de[n] Kamoshida em primeira mão e quer usar o que viu no[n] Palácio para expô-lo... mas a tragédia acontece.[n][w][e]

[msg TUTORIAL_MSG05 [Il primo colpo: Kamoshida]]
[s]Incapaz de lidar com o abuso de Kamoshida,[n][clr 2]Shiho Suzui[clr 27] se joga do telhado da escola,[n]convencendo sua melhor amiga Ann,[n]a parar o abuso de uma vez por todas .[n][w][e]

[msg TUTORIAL_MSG06 [Il primo colpo: Kamoshida]]
[s]Morgana então revela que [clr 2]é possível[n]mudar o coração de Kamoshida[clr 27] roubando dele a[n]fonte de seus desejos: seu [clr 2]Tesouro[clr 27]. E então[n]eles voltam para seu palácio.[n][w][e]

[msg TUTORIAL_MSG07 [Il primo colpo: Kamoshida]]
[s]O grupo derrota o senhor do palácio e[n] rouba seu tesouro, fazendo com que o verdadeiro Kamoshida[n] faça um pedido público de desculpas e se entregue às[n] autoridades.[n][w][e]

[msg TUTORIAL_MSG08 [Il primo colpo: Kamoshida]]
[s]Percebendo que eles podem usar seus novos[n] poderes para ajudar aqueles incapazes de se defender,[n] [f 4 2] e os outros concordam em continuar[n] sua missão como os Phantom Thieves.[n][w][e]

[msg TUTORIAL_MSG09 [Il primo colpo: Kamoshida]]
[s]Embora tenham algumas preocupações sobre o[n]futuro, sua vontade de ferro os encoraja a[n]abraçar novas existências como[n][clr 2][f 4 28][clr 27], os Ladrões Fantasmas da Justiça.[n][w][e]

