[msg TUTORIAL_MSG01 [Bônus e recompensas do desafio de batalha]]
[s]Existem 3 tipos de recompensas que podem ser obtidas[n]nos desafio de batalhas, dependendo da pontuação final.[n]Cada uma delas só pode ser obtida uma vez.[n][w][e]

[msg TUTORIAL_MSG02 [Bônus e recompensas do desafio de batalha]]
[s]Você não pode fazer um Hold Up ou um All-Out Attack[n]durante um desafio de batalha. No entanto, se você cumprir[n]certos requisitos, receberá pontos de bônus.[n][w][e]

[msg TUTORIAL_MSG03 [Bônus e recompensas do desafio de batalha]]
[s]Na tela de RECOMPENSAS, use [f 1 10 3] para visualizar[n]condições de bônus e oponentes.[n]Almeje a pontuação máxima escolhendo cuidadosamente[n]membros do grupo.[n][w][e]

