[msg TUTORIAL_MSG01 [Use a lavanderia]]
[s]Usar a lavanderia fará com que o tempo passe,[n]mas você poderá lavar [clr 2]armadura suja[clr 27] por[n]400 ienes. Fazer isso irá limpá-lo e revelar seu[n]verdadeiro potencial.[n][w][e]

[msg TUTORIAL_MSG02 [Use a lavanderia]]
[s]Você pode lavar até [clr 2]quatro[clr 27] itens em um ciclo.[n]O item que você recebe é [clr 2]aleatório[clr 27].[n]Certifique-se de ir à lavanderia quando[n]você tem uma [clr 2]armadura suja[clr 27].[n][w][e]

