[msg TUTORIAL_MSG01 [Jogar videogames]]
[s]Jogar videogames vai passar[n]o tempo, mas vai melhorar diferentes habilidades[n]dependendo do título jogado.[n][w][e]

[msg TUTORIAL_MSG02 [Jogar videogames]]
[s]Os videogames são compostos de vários níveis.[n]Ao completar um nível, você preencherá um[n]ícone de cartucho. Assim que todos os[n]ícones estiverem preenchidos, você terá concluído o jogo.[n][w][e]

