[msg TUTORIAL_MSG01 [Tela de Batalhas de Desafio]]
[s]Durante os desafios de batalha, você pode ver[n]a pontuação atual, a pontuação necessária para uma[n]recompensa e as condições para obter pontos bônus.[n][w][e]

[msg TUTORIAL_MSG02 [Tela de Batalhas de Desafio]]
[s]Se você perder um desafio de batalha, o jogo não termina.[n]Se você acha que não pode vencer,[n]pressione [f 1 10 50] no menu "Mudança de tática" para escapar.[n][w][e]

[msg TUTORIAL_MSG03 [Tela de Batalhas de Desafio]]
[s]As pontuações dos desafios de batalha são baseadas no dano[n]infligido. Tente uma pontuação alta causando dano massivo.[n][w][e]

