[msg D_TUTORIAL_16_mes01 [Lasers infravermelhos]]
[s]Você pode localizar lasers infravermelhos com o Terceiro olho.[n]Se você encontrar uma lacuna larga o suficiente,[n]você pode passar por ela com [clr 2][f 1 10 22][clr 27].[n][w][e]

[msg D_TUTORIAL_16_mes02 [Lasers infravermelhos]]
[s]Isso também pode ser feito [clr 2]segurando [f 1 10 22] ao[n]aproximar-se[clr 27], mas lembre-se de que [clr 2]você só pode[n]passar se houver bastante sala[clr 27].[n][w][e]

