[msg TUTORIAL_MSG01 [Usando locais de encontro]]
[s]Existem vários [clr 2]pontos de encontro[clr 27] na cidade,[n]incluindo lojas, locais de eventos, pontos de referência[n]e muitos mais.[n][w][e]

[msg TUTORIAL_MSG02 [Usando locais de encontro]]
[s]Cada Confidente tem um local de encontro favorito.[n]Ao visitá-lo juntos, seu vínculo com a pessoa se fortalecerá[n]mais do que o normal.[n][w][e]

[msg TUTORIAL_MSG03 [Usando locais de encontro]]
[s]Você pode descobrir novos pontos de encontro, quando[n]é convidado pelos Confidentes, ou lendo nos livros.[n]Tente descobrir o máximo possível.[n][w][e]

