[msg D_TUTORIAL_34_mes01 [Sementes dos Desejos]]
[s]Em um Palácio, existem locais onde se concentra a[n]cognição do dono do Palácio.[n][w][e]

[msg D_TUTORIAL_34_mes02 [Sementes dos Desejos]]
[s]Devido à distorção cognitiva,[n]os itens são chamados de "Sementes dos Desejos", e irão aparecer[n]nesses locais.[n][w][e]

[msg D_TUTORIAL_34_mes03 [Sementes dos Desejos]]
[s]Existem 3 Sementes dos Desejos em cada palácio.[n]Ao obter uma semente, você recuperará uma[n]pequena quantidade de SP. Use [clr 2][f 1 10 53][clr 27] para abrir[n]o mapa e ver as sementes coletadas.[n][w][e]

