[msg TUTORIAL_MSG01 [Antes de se infiltrar em um palácio]]
[s]Verifique seu progresso com a opção[n][clr 2]Realizar uma reunião[clr 27]. Ouça as opiniões de seus[n]amigos e decida o melhor caminho a seguir.[n][w][e]

[msg TUTORIAL_MSG02 [Antes de se infiltrar em um palácio]]
[s]Selecionar [clr 2]Infiltrar Palácio[clr 27] levará você ao[n]Palácio. Você não pode comprar itens dentro dele, então[n]certifique-se de estar bem preparado.[n][w][e]

[msg TUTORIAL_MSG03 [Antes de se infiltrar em um palácio]]
[s]Quando você voltar de um palácio, irá ser noite.[n]Se o tempo acabar, o [clr 2]fim de jogo[clr 27] começará.[n]Sempre fique de olho no tempo restante.[n][w][e]

