[msg TUTORIAL_MSG01 [Ataques Técnicos]]
[s]Quando você executa um [clr 2]ataque específico[clr 27] em um[n]inimigo com [clr 2]uma doença de status[clr 27], o tornará um[n][clr 2]ataque técnico[clr 27] com dano aumentado e[n]chance de derrubar o inimigo.[n][w][e]

[msg TUTORIAL_MSG02 [Ataques Técnicos]]
[s]Realizar um [clr 2]ataque técnico[clr 27] requer o cumprimento[n]de várias condições, que podem[n]ser consultadas [clr 2]na lista de habilidades[clr 27] ou[n][clr 2] em seu cursor[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Ataques Técnicos]]
[s]No entanto, se as afinidades do inimigo [n]não forem conhecidas, [clr 2]as condições não serão mostradas[clr 27].[n][w][e]

[msg TUTORIAL_MSG04 [Ataques Técnicos]]
[s]Mais informações você pode encontradas em[n]"[clr 2]Variações de técnicas de ataque[clr 27]".[n][w][e]

