[msg TUTORIAL_MSG01 [Obstáculos especiais nos Palácios]]
[s]Às vezes, você encontrará [clr 2]alguns[n]obstáculos intransponíveis nos Palácios, que o forçarão[n]a interagir com o alvo no mundo real[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Obstáculos especiais nos Palácios]]
[s]Saia do Palácio para procurar o obstáculo.[n]Visite oportunamente os Palácios para procurar[n]obstáculos e superar desafios antes que[n]o tempo acabe.[n][w][e]

