[msg TUTORIAL_MSG01 [Ranking de Técinas]]
[s]Se você [clr 2]tiver sucesso em uma jogada[clr 27],[n]sua posição no [clr 2]Ranking de técnicas[clr 27] aumentará.[n][w][e]

[msg TUTORIAL_MSG02 [Ranking de Técinas]]
[s]À medida que seu Ranking de Técnicas aumenta, o[n]dano causado por um acerto de [clr 2]Tecnologia[clr 27] em[n]batalha também aumentará. Se a classificação aumentar[n]novamente, os inimigos também serão [clr 2]derrubados[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Ranking de Técinas]]
[s]Você pode aprender [clr 2]spin shots lendo livros[clr 27] e[n][clr 2]usando o equipamento apropriado[clr 27].[n]spin shots requerem[n]um certo valor de [f 4 11 2][clr 26][f 4 12 2][clr 27].[n][w][e]

