[msg TUTORIAL_MSG01 [Confidentes e fusões]]
[s]Quando você mescla uma Persona do mesmo Arcano[n]como um Confidente com o qual você se ligou,[n]essa Persona ganhará experiência adicional após[n]sua criação.[n][w][e]

[msg TUTORIAL_MSG02 [Confidentes e fusões]]
[s]Essa experiência bônus é chamadas de [clr 2]Surto do Arcano[clr 27].[n]Quanto mais alto for a sua afinidade com o confidente[n]relacionado, mais experiência a Persona receberá.[n][w][e]

