[msg TUTORIAL_MSG01 [Legami con i Confidenti]]
[s]Para prevalecer na batalha, você precisará de[n]personas poderosos. Estes se tornarão mais fortes[n]através de cada um dos [clr 2]laços com os Confidentes[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Legami con i Confidenti]]
[s]Além disso, à medida que seus laços crescem,[n]seus confidentes aprenderão habilidades únicas.[n]Certifique-se de gastar o tempo necessário[n]fortalecendo esses laços especiais.[n][w][e]

